### ISSUE TITLE
Investigate whether or not to add Custom View Types: Binary, "Open Seadragon", and PDFjs to our content types

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#100]
The "Repository Item" out of the box has five total view types selected.  These are Default, Binary, "Open Seadragon", PDFjs, and Teaser.  All other content types as well as the three that we have defined "ASU Repository Item", "Collection", and "Institution" have only Default and Teaser selected.

Determine where the additional Repository Item view types are being used -- and if necessary, create these on the items that we have created.

**Comment by elizoller** [comment]
This has been accomplished by following the model of the islandora repository items. we have display modes for
- default view
- document view -> pdfjs
- image view -> openseadragon
- full metadata view
- additional view modes that display only the title and viewer
- teaser
- search result

we will still likely need additional view modes for the citations/reuse page
i think we've already covered this, or it will be in #126
