### ISSUE TITLE
Create a role for "Ask an Archivist"

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#101]
This role would be able to access all of the information for all collections - and potentially have some additional permissions as well.

**Comment by elizoller** [comment]
can you elaborate on this one for me? do you mean view all collections - even unpublished ones?

**Comment by elizoller** [comment]
Right now we have roles for
- metadata manager
- depositor
- content approver

I can foresee those needing to be changed as the workflows are getting situated.

**Comment by wgilling** [comment]
I believe that this was a need that came out of the repo dev or another similar meeting... essentially that the people who represent "Archivists" be able to view all of the items for all of the collections regardless of the collection creator's potential restriction to visibility of that collection and the items. I believe that this would allow archivists to browse AS WELL AS search for content because of this permission -- even when that content is restricted.

I feel like I did not understand the exact nature of the initial ask from that meeting -- and we may need to better define this need.

**Comment by elizoller** [comment]
Yeah, that’s the permissions that a content approver has. Just a matter of naming really. They have to be able to see all of the things.

**Comment by elizoller** [comment]
Closing this since the role already exists
