### ISSUE TITLE
Compound object children cause broken Feedback form

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#103]
Because the assumption that an object to collection relationship is the "MemberOf" relationship, but with compound object child objects, they are a MemberOf their parent object -- which is usually associated with a collection (if not always).

Perhaps the ancestors field needs to be used for the "Item" selection box that is at the top of the "Feedback" Webform.

**Comment by wgilling** [comment]
Upon further inspection of that feedback form, it seems to also fail to preload the Item value when an non compound object is used as well.

The url that some example nodes have that lead to the feedback form are:
http://localhost:8000/form/feedback?source_entity_type=node&source_entity_id=10&item=10 
http://localhost:8000/form/feedback?source_entity_type=node&source_entity_id=12&item=12 
The form's configuration (build) starts off with the values:

`item:
  '#type': entity_select
  '#title': Item
  '#disabled': true
  '#required': true
  '#target_type': node
  '#selection_handler': 'default:node'
  '#selection_settings':
    target_bundles:
      collection: collection
      islandora_object: islandora_object`

**Comment by elizoller** [comment]
which content type was this on?
