### ISSUE TITLE
Counting Downloads for media objects

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#108]
We need to explore how to count downloads. It's important to have the date/time for each download. We think we might be able to take advantage of Matomo for this.
That will involve adding classes to download links so matomo can count it.
If Matomo doesn't handle it, we'd need to add a new table in the database to write to for downloads.

**Comment by elizoller** [comment]
Matomo tracking API docs: https://developer.matomo.org/api-reference/tracking-api

**Comment by wgilling** [comment]
Discussions in the Islandora slack seemed to identify a big problem with Matomo not being able to track the related nodes when viewing media objects.

The download counts could be queried via AJAX and on any given node, this would relate that node to its media and then call Matomo API to get the download value to display.

**Comment by wgilling** [comment]
Bryan Brown at Florida State University wrote some modules that may be very useful to get the download counts.

https://github.com/fsulib/islandora_matomo_blocks
https://github.com/fsulib/islandora_matomo_services

**Comment by wgilling** [comment]
added a block to the module asu_item_extras that will call the islandora_matomo_services module API to get the value for use in our item twig templates.
