### ISSUE TITLE
Collections A-Z

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#109]
Implement collections A-Z page based on Jordyn's mockup: https://99m7x4.axshare.com/#g=1&p=collections_a-z

**Comment by elizoller** [comment]
Key features include
- the "glossary" or clickable links by first letter in the title (after stop words?)
- a search/filter by collection title + description

**Comment by wgilling** [comment]
I used a different branch that is up to date with the latest in the **develop** branch (as of 8:30am this morning). The new branch is called "glossary_view" https://github.com/asulibraries/islandora-repo/tree/glossary_view.

**Comment by elizoller** [comment]
Remaining cleanup on collections a-z page

- [ ] buttons push to bottom of box
- [ ] make h2 smaller and bolder (1.3rem, font-weight: bold)
- [ ] truncate the description after 4-5lines ish
- [ ] fix split to col-3 and col-9
- [ ] make thumbnails square
- [ ] fix wonky width on the thumbnails
