### ISSUE TITLE
Bulk creation/ingestion via MODS XML

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#11]
Use case: As an administrator, I want to bulk ingest digital assets and associated metadata into the digital asset delivery system, and have the digital asset delivery system associate the assets to their corresponding metadata, so that I can efficiently provide end-users with access to digital assets.

**Comment by wgilling** [comment]
Prerequisite is the metadata fields.

I believe that we will need to standardize the CSV fields, expected file format for each object type, and any file storage requirements in order to be ingested via bulk ingest methods.  Research also needed in ingesting via bulk ingest methods.

**Comment by elizoller** [comment]
On a collection by collection basis, bulk creation (and update) of records can happen via the migrate API - this requires developer setup of YAML configuration. I don't consider this meeting the requirement of this use case.

**Comment by elizoller** [comment]
The metadata unit has decided the preferred method of working with records outside of the system is through MODS XML. This will require importing records from a zip of MODS xml files.
migrate_plus already supports XML
migrate_source_ui allows uploading a file for an existing migration
if we write a migration from MODS xml into the drupal fields and then allow metadata staff access to the migrate_source_ui interface (at http://localhost:8000/migrate_source_ui), they could initiate a migrate through the UI
we'd need to add some kind of migrate/source plugin to unzip a zip file for this to work in a bulk sense - or perhaps even simpler - use a single file with a parent element around it like `<collection><mods1/><mods2/></collection>`
writing a migrating for mods xml to drupal fields could potentially be endless so the work will be scoped to supported fields in the repository.

**Comment by elizoller** [comment]
i **think** we can close this with the merge of #294
