### ISSUE TITLE
Collection Home Page

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#111]
Ticket for the implementation of the collection "home" page
Mockup here: https://99m7x4.axshare.com/#g=1&p=collection_-_home
Significant features include
- display of collection title, thumbnail, and description
- sidebar with about this collection, explore/search within collection box, share box, and collaborating institutions (aggregated from those applied at the child items)
- about this collection boxes (counts/stats)
- latest additions view
- cite this collection section

**Comment by elizoller** [comment]
ties in with https://github.com/asulibraries/islandora-repo/issues/55

**Comment by wgilling** [comment]
To do:
* do a subquery of each node to get complex object children 
* potentially convert some of the stats blocks into relevant links to that box's value
* potentially count files in a different way
