### ISSUE TITLE
Theming & Styling of the Content Digest Email

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#112]
currently, the output is not fancy at all and even the table does not seem to add any alignment to the fields that are output for the Content Digest Emailings.

Depending on who will be getting these emails, we may want to discuss some of this with them to see if they have any suggestions as to what else to add to the email body -- also, should the title of this emailing be configurable, should the email subject include the date range?

**Comment by elizoller** [comment]
I can put it on the agenda for the metadata subgroup since they are the group that recommended this feature - would that be helpful?

**Comment by wgilling** [comment]
Yes. We can dig up one of the emails to show them how basic it is -- and it might be nice to show them the diff links page itself that shows the difference between any two revisions... if you have the VM still spinning, could you keep that around until the meeting?

**Comment by elizoller** [comment]
<img width="812" alt="Screen Shot 2020-07-15 at 10 04 37 AM" src="https://user-images.githubusercontent.com/5439169/87574126-c9afa100-c682-11ea-978d-6debfeda4df9.png">

**Comment by elizoller** [comment]
Yeah, i have the VM, so i could show how the view works 👍

**Comment by wgilling** [comment]
I could write a twig around the view and control the output a little bit more.

The plain-text version of the emailing seems to be lacking links.

**Comment by wgilling** [comment]
aside from SMTP configuration, this should be ready to test... the code is still set up to run with EVERY CRON cycle -- comment out line #29 in order to enforce 1/day run.
https://github.com/asulibraries/islandora-repo/blob/digest_theming_112/web/modules/custom/content_change_digest/content_change_digest.module#L28-L29

To test:

1. Configure Content Change Digest settings so that at least one user will get an emailing (making sure that the user's **Opt out of "Content Changed" daily email digest** is not checked)
2. Edit that user's email address to be a real email that you can receive
3. Make changes to at least 2 objects in the last 24 hour period... 
4. click the [Run cron] button on the "System status" page http://localhost:8000/admin/reports/status
