### ISSUE TITLE
Display the downloads for any given item

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#116]
add the downloads to the item page according to the wireframe

**Comment by elizoller** [comment]
suggested to use https://getbootstrap.com/docs/4.5/components/button-group/#nesting styling and to use islandora generated derivatives from houdini rather than drupal image styles if possible.

**Comment by dflitner** [comment]
https://getbootstrap.com/docs/4.5/components/dropdowns/ Is more direct, I think.

**Comment by wgilling** [comment]
In order to handle multiple JPG or PNG deriviatives as image sizes of differing sizes these can be added to the System | Actions config here admin/config/system/actions.

**Comment by elizoller** [comment]
@dflitner can we close this?

**Comment by dflitner** [comment]
I forgot to tag the last commit with this issue, sorry.

We can close it unless we want to use this issue to keep track of further refinements to the download button such as not showing a dropdown when there's only 1 download.

**Comment by elizoller** [comment]
Opened a new issue for this so we can keep clear what is for the MVP and what will be enhancements after the fact.

**Comment by elizoller** [comment]
More work on this here: https://github.com/asulibraries/islandora-repo/commit/bd63d615bb6e6582f3ed0dff38900ae7bf8f17ad
