### ISSUE TITLE
Aggregate search capabilities - KEEP, ASTRA, and dataverse

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#122]
The landing page and if there is a separate Search page should offer an aggregate search to 
 - Search all digital content
 - KEEP (the IR)
 - ASTRA (the DC)
 - Dataverse (data repository)

I would assume that the default choice should be to search ALL

There would need to be a way to display the results of the aggregate search within the Drupal system -- We should borrow or reuse code for the Bento system if possible.

**Comment by elizoller** [comment]
I don’t know that we’ll be able to directly use code from the Bento but I think the concepts will be the same. Just making a note before TRUST is ready, we’ll likely want to do a box with results from the legacy repository. Technically speaking, I’m thinking if we connect all three solr servers + indexes then we can probably use views that create a block for each one. Then a page with all three blocks into three columns (or whatever design). I’m thinking the blocks can each have a contextual filter to pull in the query term. Just some initial thoughts without testing anything. I suspect firewalls will need to be opened to allow this kind of solr search. Alternatively without connecting directly to solr, we could use search API. But that might require a little custom development.

**Comment by elizoller** [comment]
Decided to roll with "services" infrastructure for communicating with dataverse and legacy repository apis - see pr #139

**Comment by elizoller** [comment]
I will close this as thanks to @wgilling on #139 we have KEEP, Dataverse, and Legacy Repository working in a bento style search. I'll create a new ticket for adding the to-be-named digital collections site when that one is up and running.
