### ISSUE TITLE
Altmetrics Donut

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#123]
This is a feature we have in the existing repository - display of the Altmetrics donut where applicable.
see https://repository.asu.edu/items/42203 for example

**Comment by elizoller** [comment]
The current repo uses a template like 
```
<div data-badge-details="right"
                 data-badge-type="donut"
                 {% if item.doi %}
                    data-doi="{{ item.doi }}"
                 {% else %}
                    data-handle="{{ item.handle }}"
                 {% endif %}
                 data-hide-no-mentions="true"
                 class="altmetric-embed"></div>
```
Not directly applicable but probably gives us some idea

**Comment by wgilling** [comment]
do this only for asu_repository_item objects

**Comment by elizoller** [comment]
we're bringing this to design in terms of where to put it, what altmetrics badge to use

**Comment by elizoller** [comment]
design says medium badge

**Comment by wgilling** [comment]
Added the CSS to make it look like the one on the altmetric website.
