### ISSUE TITLE
Provide a default icon/thumbnails for items and collections

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#125]
This same concept appears in search results display as well as to display individual items in a complex object.

The view could display the media thumbnail for objects that have them and when they have no results, then it could display the "font awesome" icon that corresponds to a media type.

**Comment by elizoller** [comment]
Icons based on 5 “types” of media are
-Image
-Audio
-Video
-Document
-File
-things that don’t have media at all (Metadata only item) - only displays in search results (full view - Let the content go full width if no preview available)
-Complex object - multi file icon

Jordyn pick icons from FontAwesome

**Comment by wgilling** [comment]
a bit more twig manipulation needed to make the view and permanent link links actively go to the correct destination...

I am going to change to the new "citation_block" branch to address what we just discussed in our dev meeting today.

**Comment by elizoller** [comment]
more work here: 
https://github.com/asulibraries/islandora-repo/commit/bec2b07e636b4dac7c428f39e251af59572c9fdf

**Comment by elizoller** [comment]
Image 
<i class="far fa-file-image"></i>
Audio
<i class="far fa-file-audio"></i>
Video
<i class="far fa-file-video"></i>
Document
<i class="far fa-file-alt"></i>
File
<i class="far fa-file"></i>
Complex object (multiple file)
<i class="far fa-copy"></i>
Collection
<i class="far folder-open"></i>
