### ISSUE TITLE
Theming of the Single Item Display Page

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#126]
Putting this issue here to keep track of work for the theming of the single item page.
Working off: https://99m7x4.axshare.com/#g=1&p=item__image_ and https://99m7x4.axshare.com/#g=1&p=item__ocr_
with the details (brief metadata) section to include the following fields:

- Title
- Description (limit of 250 char)
- Author/Contributor
- Date Created
- Subject(s)
- Resource Type
- Collection memberships
- Collaborating Institutions
- Reuse Permissions
- Identifiers

**Comment by dflitner** [comment]
Since we've determined to use a single view mode for as many resource types as possible, should I just work on the default view mode instead of using the asu_image view mode I'm currently using? 

Then we can make new view modes for special cases that don't fit such as collection and maybe complex object.

**Comment by elizoller** [comment]
Using the default view mode makes sense to me

**Comment by dflitner** [comment]
Making a note that we are going back to multiple view modes per type of viewer they use. We would have to add logic to the template files to display a viewer and/or different fields so it makes sense to use Context for the logic instead and use different view modes.

**Comment by elizoller** [comment]
for now oai link should be something like: https://repo-dev.aws.lib.asu.edu/oai/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:repo-dev.aws.lib.asu.edu:node-41

**Comment by dflitner** [comment]
Ok! I'll add that to the templates.
________________________________

**Comment by elizoller** [comment]
- [ ] remove the citations sidebar block
- [ ] remove the print/share from the full body content area
- [ ] add the preferred citation with copy bit in the full body
- [ ] hide/remove the citations separate page
- [ ] add statement of responsibility under preferred citation in full body
- [ ] remove show all pages in sidebar 
- [ ] replace start reading with Explore document

**Comment by dflitner** [comment]
I got overenthusiastic and pushed too fast. Still tweaking the css and I want to try to merge develop in so I can fix the label display as well.

**Comment by elizoller** [comment]
added template for default with fe1480c90e1620fec777135b0777bc74de8ba69a
i think this can be closed now
