### ISSUE TITLE
Related Item Field

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#127]
The metadata group has proposed a related item field which can contain one of three things
- a reference to an existing asu repository item in the system
- a string of text
- a URI to another object in the wild
There are different possibilities for mapping these objects, such as mods:relatedPreceding, mods:relatedSucceeding, and dcterms:relation. They would like to allow the user to choose the relation.
Because of the notion of picking a relation, and because we originally only proposed referencing an existing asu repository item in the system, I used the Typed Relation field to create this field.
With the addition of allowing a string or a URI to outside the system, it becomes more complicated.

**Comment by wgilling** [comment]
this module is currently deployed under web/modules/custom/soft_delete

The configuration screen still displays the content types above the workflow states for each in separate sections -- and it would be nice to merge these two options together in an alternating fashion "enable Soft Delete handling for {content_type}" (checkbox) followed by a select box to pick which moderation_state value to set from the set of workflow states available to this content type.

There should be a minimal README before this can be released to the community.

**Comment by elizoller** [comment]
What if we use a typed relation with its own vocabulary and inside that vocabulary terms could have URIs or not have URIs - and those URIs could be internal or external

**Comment by elizoller** [comment]
Related item field now is a taxonomy reference to its own vocabulary called related items. terms in that vocabulary have the following fields:
- label (required by all, accommodates simple strings)
- external item - url field (accommodates external urls)
- internal item - entity reference (accommodates internal objects)
