### ISSUE TITLE
Add Digital Collections Site to Bento

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#141]
As a follow-up to https://github.com/asulibraries/islandora-repo/issues/122
We will need to add the digital collections site to the bento search results

**Comment by wgilling** [comment]
I can take this after we know the domain -- I assigned it to myself.

**Comment by elizoller** [comment]
Ok, excellent. I imagine it’ll be a little while because we aren’t planning to spin that site up until closer to the end of the year. I marked this as part of the DC milestone.

**Comment by wgilling** [comment]
+1

**Comment by elizoller** [comment]
undo the change here: 9aeb9296aa18fb063236e910b53928bfe15cd4b6 to add back the block for the digital collections site

**Comment by wgilling** [comment]
the second Islandora block has been enabled again and a bit of CSS and template markup code has been added to wrap each link in a div that has the title (hint) of the full text but this will function to restrict the link to a single line and display an ellipsis if the text is too long for a single line.
