### ISSUE TITLE
Convert site to 1224px overall width

### ISSUE THREAD

**Issue by dflitner** [asulibraries/islandora-repo#148]
The wireframes assume a page width of 1200px and our current theme is set to about 1110px. ASU Web Standards 2.0 has widths calculated for a variety of breakpoints, that also target bootstrap components for flow at those breakpoints. The base container width is 1224px.

At some point, we should discuss when and how far we want to bring the repository theme into alignment with WS 2.0.

From Sarah Hough at the Hub:

> All, I do want to be super clear that the unity design system is flexible as long as the grid, spacing and typography standards are being followed. Solutions have been designed for common needs, like cards, lists, carousels, forms, etc, but that doesn't mean the UI kit is comprehensive of every possible standards-aligned solution. If you have a component needed by your unit that isn't part of it, the hope is that can become part of the kit to benefit the community, or an example of how the standards can be executed beyond the prescribed components.

**Comment by elizoller** [comment]
@dflitner will we get this with the transition to unity as part of #356 ?

**Comment by elizoller** [comment]
@dflitner do you if unity bootstrap will do this for us?

**Comment by dflitner** [comment]
Yes, if we use the Unity files, _grid.scss has the containers set to max-width: 1224px for desktop.

**Comment by elizoller** [comment]
<img width="369" alt="Screen Shot 2021-07-06 at 10 09 11 AM" src="https://user-images.githubusercontent.com/5439169/124640405-3860ae00-de42-11eb-8843-4750638b1bcc.png">
i believe this is applied now with the inclusion of #408 
@dflitner please re-open if this is not the case
