### ISSUE TITLE
Change Full Metadata URL

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#154]
Change `/node/nid/full-metadata` to `/items/nid/metadata`
starts in asu_item_extras.routing.yml but is mentioned in several templates
@dflitner suggests keeping it dynamic in templates with something like
`{{ path ~ metadata }}`

**Comment by dflitner** [comment]
For the template, I think we can just do `href="{{ url }}/metadata"`. That's the token that the default theme file uses for linking the page title and it seems to output the same value as `{{ path('entity.node.canonical', {'node': node.id}) }}`, but it's more concise.

**Comment by elizoller** [comment]
part of this is in https://github.com/asulibraries/islandora-repo/commit/b7abaffdb79062cfc375c3d16b14eb79644c65f1#diff-b357ce42e890676de0e6f59e4edb687a
