### ISSUE TITLE
Content model for administrative and exhibit purposes, ie. “set”

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#16]

**Comment by elizoller** [comment]
propose making this a separate content type with a relationship on the repository item level to one or many nodes of that content type

**Comment by dflitner** [comment]
I was thinking of this the other way around. A separate content type with an entity reference field to repository items (and collections?).

Depending on how design goes, there could be multiple templates available which are triggered with a select field and context/css.

However, I suppose it might be easier to pick multiple repo items for an exhibit if the field was on repo item and this was done with VBO. Especially with the number of exhibits vs the number of repo items you'd have to query for the entity reference. 

I think I just talked myself out of this suggestion but I'm going to leave this comment anyway in case it helps. :)

**Comment by elizoller** [comment]
Haha - your thought about the number of exhibits vs number of repo items is one of the main reasons I also think it makes sense to have the repository item contain the relationship to the "set"
