### ISSUE TITLE
Sitemap for SEO

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#17]
Use case: The system should have a sitemap that can be published to Google and other search engines to optimize SEO. simple_sitemap may get us most of the way there

**Comment by elizoller** [comment]
https://www.drupal.org/project/simple_sitemap

**Comment by elizoller** [comment]
module is downloaded and enabled via commit above but needs configuration

**Comment by elizoller** [comment]
@wgilling  - do you know where we are on this? i can't remember where we ended up on it - it seems to be enabled but i'm getting a 404 when i go to `sitemap.xml`

**Comment by wgilling** [comment]
I never got into this issue very far.

I will test again, but the test I just did also gave me a 404... but I don't have any content and the sitemap.xml is supposedly generated during a CRON run (even though there is supposedly a way for it to create this when clicking Save on the Settings page http://localhost:8000/admin/config/development/devel

**Comment by elizoller** [comment]
Yeah, I think you can manually queue the items here: http://localhost:8000/admin/config/search/simplesitemap
and it seemed like the sitemap should be at sitemap.xml or the variant name like default/sitemap.xml (got this from http://localhost:8000/admin/help/simple_sitemap - which says "The sitemaps are accessible to the whole world under [variant name]/sitemap.xml. In addition to that, the default sitemap is accessible under /sitemap.xml.")
for whatever reason, its working for me now - as in not a 404. but i only have one url and its jut https://default which is obviously not right so i think it requires more configuration.
i don't think this is super high priority so maybe we can move it to a later milestone?

**Comment by wgilling** [comment]
Yes it is -- here is my xml:

<?xml version="1.0" encoding="UTF-8"?>
--
  | <?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>
  | 
  | <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  | <url>
  | <loc>http://localhost:8000/node/1</loc>
  | <lastmod>2020-07-15T11:32:59-05:00</lastmod>
  | <priority>0.5</priority>
  | </url>
  | </urlset>

**Comment by wgilling** [comment]
it didn't like that .. it stripped out all the tags - here is the code view for that
`<?xml version="1.0" encoding="UTF-8"?>
--
  | <?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>
  | 
  | <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  | <url>
  | <loc>http://localhost:8000/node/1</loc>
  | <lastmod>2020-07-15T11:32:59-05:00</lastmod>
  | <priority>0.5</priority>
  | </url>
  | </urlset>
`

**Comment by wgilling** [comment]
why does everything not do what I want? 

```
<?xml version="1.0" encoding="UTF-8"?>
--
  | <?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>
  | <!--Generated by the Simple XML Sitemap Drupal module: https://drupal.org/project/simple_sitemap.-->
  | <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  | <url>
  | <loc>http://localhost:8000/node/1</loc>
  | <lastmod>2020-07-15T11:32:59-05:00</lastmod>
  | <priority>0.5</priority>
  | </url>
  | </urlset>
```

**Comment by elizoller** [comment]
cool - if you're seeing stuff then we might be most of the way there. with your experience with SEO - are there are additional things /changes we need in the sitemap?

**Comment by wgilling** [comment]
Great question! I updated my node to have more values than title and description but the sitemap.xml is identical - I thought that there was a way to configure which fields are made into values or on the actual node | Edit page in that "Simple XML Sitemap" section (??), but I would think that some other values could help SEO.

**Comment by wgilling** [comment]
@elizoller is handling the configuration for this will need to be set to the base url of the staging and production sites and then exported to the specific environment.
