### ISSUE TITLE
Make entire area of list items clickable in sidebar navigation

### ISSUE THREAD

**Issue by dflitner** [asulibraries/islandora-repo#179]
They all currently have hover effects but the whole area isn't clickable. This isn't great UX. Just need to make the `<a> and <li>` display: block or use display:flex maybe.

Also need some clarification on separators from Jordyn. Wireframe is inconsistent but might be intended.

**Comment by dflitner** [comment]
This isn't as simple as it should be due to the permalink link. Need to modify that or work around it.

**Comment by elizoller** [comment]
@dflitner do you think this will be resolved with the move to ws2.0?

**Comment by dflitner** [comment]
Depending on what kind of ws2.0 component or style we end up applying, it should work out but we'll need to keep an eye on it. 
What can help with the existing code is configuring the permalink HTML to use a single span instead of two but almost every clickable item in the sidebar needs slightly different CSS because they or their containers are all so different. 

The padding needs to be removed from the containers and applied to the li or clickable span to expand the clickable area and those should be 100% width of the containing li.

**Comment by elizoller** [comment]
i actually think it is resolved: see https://keep.lib.asu.edu/about/describe when i hover over anywhere in the sidebar nav block it is the appropriate link. @dflitner can you confirm?

**Comment by dflitner** [comment]
Those work great! (I think the font size/weight might be a bit off? See [Storybook Sidebar](https://unity.web.asu.edu/@asu-design-system/bootstrap4-theme/index.html?path=/story/components-sidebar--sidebar-navigation))

However the initial ticket was talking about the sidebar on item pages such as https://keep.lib.asu.edu/items/141219. I'm afraid they have inconsistent styling even among themselves. I had to quit when I first tried to fix them because the links were generated in so many different ways I couldn't figure out how to apply the appropriate styling - and there were bigger fish to fry at the time.

**Comment by elizoller** [comment]
ok, thanks. i'll look into both of those.

**Comment by elizoller** [comment]
first part fixed with ff1d756e

**Comment by elizoller** [comment]
![Screen Shot 2021-07-06 at 3 07 03 PM](https://user-images.githubusercontent.com/5439169/124672417-dd43b100-de6b-11eb-9f21-60b44ecde36d.png)
thats a screenshot when hovered on Reorder Items
