### ISSUE TITLE
Count streams and/or interactions with players in Matomo

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#195]
This ticket encompasses tracking in Matomo custom "events" when there are interactions with players.
- [x] play on video
- [x] play on audio
//- [ ] play on remote video
//- [ ] what would we want to track about pdfjs?
//- [ ] what would we want to track about openseadragon?

Matomo event documentation: https://matomo.org/docs/event-tracking/
Video on play event to hook into: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play_event

**Comment by wgilling** [comment]
Audio and Video elements seem to track the play event just fine, but the javascript code handling of remote_video media is not catching the <video> element for some reason. The HTML for an example item that is using a remote_video is:
```
<div id="player" style="width: 100%; height: 100%;">
  <div class="html5-video-player ytp-exp-bottom-control-flexbox ytp-title-enable-channel-logo ytp-embed ytp-embed-playlist unstarted-mode ytp-hide-controls" tabindex="-1" id="movie_player" data-version="/s/player/51ff6aac/player_ias.vflset/en_US/base.js" aria-label="YouTube Video Player">
    <div class="html5-video-container" data-layer="0">
      <video tabindex="-1" class="video-stream html5-main-video" controlslist="nodownload" style="width: 640px; height: 480px; left: 0px; top: -480px;"></video></div><div class="ytp-gradient-top" data-layer="1">
    </div>
  </div>
  ...
</div>
```

**Comment by wgilling** [comment]
compare this to the html of an item that has a video -- using the video media type:
```
<div class="views-row">
<!-- THEME DEBUG -->
<!-- THEME HOOK: 'media' -->
<!-- FILE NAME SUGGESTIONS:
   * media--source-video-file.html.twig
   * media--video--source.html.twig
   * media--video.html.twig
   * media--source.html.twig
   x media.html.twig
-->
<!-- BEGIN OUTPUT from 'core/modules/media/templates/media.html.twig' -->
  <div>
  <!-- THEME DEBUG -->
  <!-- THEME HOOK: 'field' -->
  <!-- FILE NAME SUGGESTIONS:
     * field--node--video--source.html.twig
     * field--node--field-media-video-file--video--source.html.twig
     * field--media--field-media-video-file--video.html.twig
     * field--media--field-media-video-file.html.twig
     * field--media--video.html.twig
     * field--field-media-video-file.html.twig
     * field--file.html.twig
     x field.html.twig
  -->
      <!-- BEGIN OUTPUT from 'themes/contrib/bootstrap_barrio/templates/field/field.html.twig' -->
      <div class="field field--name-field-media-video-file field--type-file field--label-visually_hidden">
          <div class="field__label visually-hidden">Video file</div>
              <div class="field__item">
<!-- THEME DEBUG -->
<!-- THEME HOOK: 'islandora_file_video' -->
<!-- BEGIN OUTPUT from 'modules/contrib/islandora/modules/islandora_video/templates/islandora-file-video.html.twig' -->
        <video controls="controls" width="640" height="480">
          <source src="/sites/default/files/2021-07/7-Service%20File.mp4" type="video/mp4">
              <track src="/_flysystem/fedora/2021-07/captions-132218.vtt" srclang="en" label="" kind="subtitles" <="" video="">
<!-- END OUTPUT from 'modules/contrib/islandora/modules/islandora_video/templates/islandora-file-video.html.twig' -->
        </video>
      </div>
    </div>
    <!-- END OUTPUT from 'themes/contrib/bootstrap_barrio/templates/field/field.html.twig' -->
  </div>
  <!-- END OUTPUT from 'core/modules/media/templates/media.html.twig' -->
</div>
```

**Comment by elizoller** [comment]
its not in an iframe, right?

**Comment by wgilling** [comment]
YES -- it is in an iframe. Do you feel that we can alter an iframe in drupal to inject the javascript to it?? _My expectations on what can be done have lowered when I confirmed it is an iframe._

**Comment by elizoller** [comment]
no, you can't affect content inside an iframe with javascript :(

**Comment by wgilling** [comment]
For "play on remote video", we can not support that since it is in an iframe.

### openseadragon
 - many properties could be tracked such as zoom level but most of these probably don't make sense to track. 
 - good info here: https://openseadragon.github.io/docs/OpenSeadragon.EventSource.html or 
https://pdfjs.express/documentation/learn-more/events

### PDFjs
 - good info on PDFjs may be found here (as long as this is compatible with the PDFjs): https://pdfjs.express/documentation/learn-more/events
 - The PDF properties such as "pages turned" or "zoom level changes", etc., could be tracked like this
```
document.addEventListener('pagechange', function(e) {
  if (e.pageNumber !== e.previousPageNumber) {
    console.log('page changed from ' + e.previousPageNumber + ' to ' + e.pageNumber);
  }
});
```

**Comment by wgilling** [comment]
Both the openseadragon viewer and the pdfjs viewer are on pages that are already tracked within Matomo... to view the images or PDF documents that have been viewed within Matomo, simply look for their path to be tracked, for example "items/12/view" (navigate to the Behavior | Pages page, set a report Period (calendar button at the top-left), and select "items", expand the "+12" subitem, and select the row for "view" and see how many time it has been viewed during the selected period.

After merging the upcoming PR from this `islandora_matomo`.`matomo_multimedia_events_195` branch (which adds Matomo tracking for audio and video "play" events), this issue can be closed.

**Comment by wgilling** [comment]
we are going to refactor this to be a part of asu_statistics instead of the islandora_matomo module since the customizations that we have regarding item hierarchy make it a little tough to contribute to the community while keeping the code clean and optimal.
