### ISSUE TITLE
Search box submit button icons

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#197]
Search boxes should have the magnifying glass for the submit button instead of the word search
<i class="fas fa-search"></i>

**Comment by elizoller** [comment]
@dflitner  already did this for the homepage boxes - should we be doing it for all search boxes (ie. one in nav and ones on item and collection and search pages)

**Comment by dflitner** [comment]
All search buttons should say "search" rather than the magnifying glass. (For now)
