### ISSUE TITLE
Display object hierarchy, ie. breadcrumbs

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#20]
install and configure islandora_breadcrumbs

**Comment by elizoller** [comment]
Will need to test against our custom collection content type (vs repository item with label) and be sure to enable seeing the title of the current object (should just be a config change)

**Comment by elizoller** [comment]
This is enabled by default with ansible in the drupal.yml: https://github.com/asulibraries/claw-playbook/blob/master/inventory/vagrant/group_vars/webserver/drupal.yml#L81 and has associated config here: https://github.com/asulibraries/islandora-repo/blob/develop/config/sync/islandora.breadcrumbs.yml
it depends on the member_of relationship to build breadcrumbs.
Worth noting that it doesn't link create breadcrumbs from the media back to the parent node so if we want that we'd need to extend the islandora_breadcrumbs module.

**Comment by elizoller** [comment]
Breadcrumbs on media issue is here: https://github.com/Islandora/documentation/issues/1386
Although it's worth considering whether or not a front-end/non-authed user would even encounter a "media page" but instead would likely view the media on the parent node's page.

**Comment by elizoller** [comment]
Islandora Breadcrumbs do not currently support multiple parents.

**Comment by elizoller** [comment]
The member_of field is however weighted and the breadcrumb takes the lowest (first in the list) parent to display so that does kind of work.

**Comment by dflitner** [comment]
Use multiple member_of or other entity reference fields to map to multiple collections. Have one canonical/master member_of field to be the breadcrumb (need some policy/workflow around this) and then additional fields for additional collections/grants/other entities.

Can then display on an item page a block or other way to show additional collections that item is a part of.

**Comment by elizoller** [comment]
Can this be closed? Since we don't anticipate users interacting with the media pages, i don't think we're reliant on having a breadcrumb for this.

**Comment by dflitner** [comment]
Was this just for media or a general discussion about breadcrumbs? Because if it's just regarding media, then I would agree that it could be closed but if this is meant to track all breadcrumb info/discussion then we should keep it for further work on crumbs for multi-collection items, etc.

**Comment by elizoller** [comment]
General discussion about breadcrumbs. The islandora_breadcrumbs module gets us most of the way there by respecting the member_of relationship especially since we decided to separate the primary/canonical membership from other memberships. Is there another component of this that we're missing?

**Comment by elizoller** [comment]
Tammy is going to look into this from the UX perspective.

**Comment by tallgood** [comment]
Interesting though dated discussion - https://groups.google.com/forum/#!msg/islandora/ZQBsentKWyQ/ETRa-bzju08J

**Comment by elizoller** [comment]
based on what i'm seeing in the mockups here: https://99m7x4.axshare.com/#g=1&p=item__ocr_
can i assume that we're doing a structure like
ASU IR > Collections > Collection Name > Item Name
where the collection name is the primary membership?
We have Islandora breadcrumbs, but when we moved away from adaptivetheme/carapace, we lost a few other niceties:
<img width="820" alt="Screen Shot 2020-07-14 at 3 18 12 PM" src="https://user-images.githubusercontent.com/5439169/87481970-5d329480-c5e5-11ea-891d-3488f5651a62.png">
so we'll need to extend on islandora_breadcrumbs - perhaps forking it? or even extending it in a way that allows us to give features back to the module. Based on our time crunch, I might suggest that we fork or extend for our personal use and then plan to give back later on.

**Comment by elizoller** [comment]
The home link appears to be there now... so what else do we need here? a path through the `Collections` page?

**Comment by elizoller** [comment]
Initial roll out improvements to breadcrumbs
- adding the title of the item the end of the breadcrumb trail as text (not a link) on an item page
- adding the title of the collection the end of the breadcrumb trail as text (not a link) on an collection page
- renaming "Home" to "Keep"
- adding the search term in quotes on the search results pages
