### ISSUE TITLE
Custom processor needed to hide Complex Object parents in Collections facet block

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#201]
The facet for Collections is displaying complex object parents as well when any search is performed.

![Screen Shot 2020-10-08 at 2 39 38 PM](https://user-images.githubusercontent.com/19391126/95518806-b27a0a00-0978-11eb-9094-a93ec812c27f.png)

A custom processor would have to display ONLY the related "isMemberOf" items that are content_type = "Collection"

A possible issue might be that when all of the the items that are suppressed are Complex Object parents -- would this processor be able to hide the block? *(assuming that a facet block that provides no filters would be confusing)

**Comment by elizoller** [comment]
main work is here: b2eeeb7c70442f6501f795f241728dc4a423b73a

**Comment by elizoller** [comment]
closed with b2eeeb7c70442f6501f795f241728dc4a423b73a
