### ISSUE TITLE
Collections display on items includes complex object parents

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#204]
<img width="985" alt="Screen Shot 2020-10-09 at 12 10 09 PM" src="https://user-images.githubusercontent.com/5439169/95622461-69818e80-0a28-11eb-9409-108ef6e0cb97.png">
it currently shows the complex object parent instead of the parent collection

**Comment by wgilling** [comment]
This is done and the code was done on the develop branch.

**Comment by elizoller** [comment]
just a note that this requires the children of complex objects to have the child of complex object field set to true
