### ISSUE TITLE
Facet styling cleanup

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#206]
<img width="397" alt="Screen Shot 2020-10-12 at 3 22 26 PM" src="https://user-images.githubusercontent.com/5439169/95795271-ce461e80-0c9e-11eb-8f9b-9a7e365b6cde.png">
two things here:
- the counts should be aligned with the top of the facet
- the wrap should not push the number to the next line (like programs and communities)

**Comment by wgilling** [comment]
please ignore the commit https://github.com/asulibraries/islandora-repo/commit/96d3f0fb960c42c732789faf36dffa9478f9229d -- it applies to #191 instead of this issue

**Comment by wgilling** [comment]
This might not be desired and I can see why the wrapped text should be allowed to be wider than the first row of text. Please advise.
<img width="786" alt="Screen Shot 2021-02-26 at 10 00 38 AM" src="https://user-images.githubusercontent.com/19391126/109330967-7eb15b00-7819-11eb-8fac-75da9b8c921c.png">

**Comment by wgilling** [comment]
the above adjustment is being reviewed by design
