### ISSUE TITLE
Ability to select multiple values for a given metadata field (determined by Metadata Application Profile)

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#22]

**Comment by elizoller** [comment]
This is simply a matter of implementing the correct configuration according to https://docs.google.com/spreadsheets/d/1pbX2LoTVwfuFQb55qUfh1rzTU69G21poZiLp3wasCo4/edit#gid=0
repeatable and required nature needs to be verified

**Comment by wgilling** [comment]
looks all good to me -- Eli will discuss the Language field with the metadata team on Wed April 1st.
