### ISSUE TITLE
Associate a User with their Orcid ID

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#224]

**Comment by wgilling** [comment]
Likely need to add a field to the user object to store the Orchid ID. First step is just to store the field.

**Comment by wgilling** [comment]
There is already a person entity field `field_orcid_id`. When should this value be stored in this field? Would it be upon login (during the hook_user_login method)? Are there any synchronization concerns between our data storage of this and what is in ORCHID for the same person?

Does this also potentially apply to linked agents who are Person type?

**Comment by elizoller** [comment]
i think at this point there isn't anything automated we can do. i think allowing the user to add their own orcid id to their account is a start.
in the future it'd be great if we could harvest citations from orcid and see if we can load the articles if they are OA, but thats a WAY future enhancement

and yes i think we may need to consider how linked agents and users are connected since that could be the case. that kind of connection would allow us to, for example, have a "profile" like page for a user that would show their contributed works. but that is also a future enhancement.

so i think config for the field and for it to display on the user's profile form is a good start before we have specific requirements for the other two larger features in the future
