### ISSUE TITLE
Link/Button/Form to create a taxonomy term from the node add/edit page

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#236]
For certain fields such as agent and subjects and genre, it would be helpful for users to be able to create taxonomy terms at the point where they are adding/editing an item. Because our taxonomy terms are complex (ie have more than just a label), I think the best option would be a link/button out to the creation form (in a new tab) so that the user could create the term, return to node add/edit tab and then use the autocomplete to retrieve the term they just added.

**Comment by elizoller** [comment]
i did a little test with a module called inline_entity_form and it kinda works - might just need some additional styling

**Comment by elizoller** [comment]
from metadata:
- don't want to see "taxonomy term" - want to see the label for the field
- want to keep the add form simple like just the label and the URI
- prefer the embedded form
- big issue is that you have to pre-select the vocabulary type

**Comment by elizoller** [comment]
i added links in the field descriptions for agents, topical subjects, and geographic subjects as a starting point

**Comment by elizoller** [comment]
looking at the fields that we use taxonomy references, there are only a few that would require custom handling for multiple taxonomy types

really only 1:
- topical subjects => subject taxonomy
- geographic subject => country codes and geographic regions, although country codes is a limited list so it'd only be geographic regions
- name title subjects => name titles
- title subjects => titles taxonomy
- temporal subjects => temporal taxonomy
- genre => genre taxonomy

multiple:
- linked agents => person, corporate body, event/conference
- name subjects => person, family, corporate body, event/conference

**Comment by elizoller** [comment]
it actually DOES handle multiple taxonomies
so the only one that doesn't work well is linked_agent because it has its OWN widget. so we'd probably need to modify that widget to do similar things

**Comment by elizoller** [comment]
Typed Relation custom widget: https://github.com/Islandora/controlled_access_terms/blob/8.x-1.x/src/Plugin/Field/FieldWidget/TypedRelationWidget.php

**Comment by elizoller** [comment]
FieldWidgets from inline_entity_form https://git.drupalcode.org/project/inline_entity_form/-/tree/8.x-1.x/src/Plugin/Field/FieldWidget

**Comment by wgilling** [comment]
This needs to be able to work with a custom field that is our linked agent field - which is a controlled_access_terms field - and the widget mentioned in the comment above extends the entity reference widget but adds the relationship type to it.

This is only needed for the typed relation field - and all of the other fields were able to be addressed with the inline entity form out of the box.

This would be similar to bits with the inline_entity_form contrib module... and it would need to let our users add a new entry.

**Comment by wgilling** [comment]
I cannot debug this on the current laptop with netbeans + xdebug.... it hits one breakpoint and then never again... any form submissions will hang until the debugger is killed. SOOOOOO FRUSTRATING. I absolutely HATE xdebug connectivity issues and "upgrades" when xdebug used to work before it was updated to 3.0.3.

**Comment by wgilling** [comment]
Ok ... xdebug never must have worked because it was always getting those errors in the apache log:

> Xdebug: [Step Debug] Could not connect to debugging client. Tried: 10.0.2.2:9003 (through xdebug.client_host/xdebug.client_port) :-(


I configured xdebug to output a log -- and these errors were in there:

> [18070] [Step Debug] WARN: 2021-06-01 22:00:05.102414: There was a problem sending 179 bytes on socket 14: Broken pipe.
> Could not connect to debugging client. Tried: 10.0.2.2:9003 (through xdebug.client_host/xdebug.client_port) :-(

This hopefully will resolve this issue -- reloading the VM after this change:

> config.vm.network :forwarded_port, guest: 9003, host: 9003 # xdebug

**Comment by wgilling** [comment]
Just got xdebug v3.x working and updated the "Configuring an Islandora environment for XDebug" document with the xdebug.ini settings.

**Comment by wgilling** [comment]
well, after rebooting it was working yesterday but today my editor is no longer stopping on breakpoints and as long as the debugger is active in my editor, the code will hang even after removing all breakpoints. I am going to try to do things that do not require any debugger.

**Comment by wgilling** [comment]
Is the code dynamically making the form mode "simple_taxo_create" because this string only occurs in the config/sync files -- and does not occur in the inline_entity_form code nor any other files under the drupal folder?

**Comment by wgilling** [comment]
added a simple_taxo_create form mode for the Family taxonomy... now, I believe all of the entities that are behind the Linked Agent field have this form mode... now this field either needs to have four separate buttons or would require a select option for which vocabulary to add to - Person, Corporate Body, Convention, or Family.

**Comment by elizoller** [comment]
Simple_taxo_create I believe is the form mode for the taxonomy  that is used for that inline embedded form

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elizoller** [comment]
If you look at the one for geographic subject, the first piece is a drop down to select the taxonomy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wgilling** [comment]
I don't see a taxonomy selection in the geo location field widget - Authority Link and Name are the only two fields that i see on this form. /admin/structure/taxonomy/manage/geo_location/overview/form-display/simple_taxo_create 

I really don't know what I'm doing here.

**Comment by elizoller** [comment]
I mean like if you go to view/edit a node, you should see under the geographic subject a drop down before the add new or add existing term buttons

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wgilling** [comment]
I see that in the edit form, but I cannot see where the select box is made that lets a user choose "Geographic Location" vocab or "Country codes" vocab. Since this is wrapped in the drupal classes for the inline form element, there must be a setting on the simple_taxo_create form mode widget or the vocabulary or somewhere else. Also, if this selector is set to "Country Codes" I don't think that it impacts what happens when the user clicks "Add new geographic subject" or "Add existing geographic subject".

**Comment by elizoller** [comment]
After some lengthy discussion (IN PERSON!!!!!) we settled around the idea that we'll keep the default widget for the typed relation field which has a relationship type dropdown and an autocomplete. as part of the helper text for the field we have links to add new people, corporate bodies, etc. we'll modify the form display for those fields to simplify them by keeping necessary fields (mostly name and uri) visible and put the rest of the less used fields inside of an accordion. i think those config changes will wrap up this ticket.

**Comment by wgilling** [comment]
the configurations for the newest approach have been pushed and I am making a PR soon.
