### ISSUE TITLE
Improve caching

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#240]
There are many places we could improve block caching.

**Comment by wgilling** [comment]
See this commit where the block had node-level based caching added: https://github.com/asulibraries/islandora-repo/commit/29ddac178e459ba0ad12feeb3238e9430b2f575b

**Comment by elizoller** [comment]
this might also be helpful https://ramsalt.com/nb/news/faster-drupal-part-1-caching

**Comment by elizoller** [comment]
We'd done various improvements to blocks and views to increase caching and the next step will be redis caching which will be encapsulated in #483
