### ISSUE TITLE
Collection search for items using field_additional_membership not showing

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#241]
In a case where an item is related to a collection using the field_additional_membership, the collection search does not show that item.

The proposed solution would be to make a new "combined ancestors" field http://localhost:8000/admin/config/search/search-api/index/default_solr_index/fields that functions a little bit like the single-level "field_combined_member_of" and a little bit like the "field_ancestors" to recursively add references to parent's parents.

In my case, I have added a node to two collections 
![Screen Shot 2020-11-10 at 2 52 26 PM](https://user-images.githubusercontent.com/19391126/98738044-5b46cb00-2364-11eb-90f8-0430ff5e2ed2.png)

On "The Top Collection (3)" search page, I can see the item reflected in the stats "Item count" box as well as in the search, but the "Secondary collection (9)" search page, I do not see the item yet it is reflected in the "Item count" box. Note: the "item count" box is doing a single-layer deep search of items that are directly related to the parent collection - this code may need to switch over to running a solr query to look at this new "combined_ancestors".

**Comment by elizoller** [comment]
@wgilling is this still an issue?

**Comment by wgilling** [comment]
This is still an issue. When an object is related to more than one collection, it only shows up on the "Primary member of" search

**Comment by wgilling** [comment]
The code and view have both been adjusted so that the query for a collection's items and search both contain items if only related via the "Additional member of" field. This includes the overview page's stats boxes for usage, files, resource types, and the latest updated timestamp for the collection's content.

**Comment by wgilling** [comment]
This view change required the addition of the views_contextual_filters_or module so that the view can filter the contextual filter on either the "Ancestors" field or the "Additional member of" field.
