### ISSUE TITLE
wrong class name for Bento Dataverse

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#242]
I cannot look at this now, but while looking for a working example of Guzzle for search faceting purposes, the Dataverse class seems to be using the Matomo name.
```
/**
 * Class DataverseApiService.
 */
class IslandoraMatomoService implements BentoApiInterface {
```

**Comment by elizoller** [comment]
what file are you seeing this? i'm not seeing it in mine

**Comment by wgilling** [comment]
somehow my local code was changed... no worries - will delete / close this issue.
