### ISSUE TITLE
Add spam protection to forms open to the public

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#244]
Add a captcha or honeypot or some other spam protection on the forms open to the public - contact and feedback forms.

**Comment by elizoller** [comment]
@wgilling any interest in this one? i think it'd be mostly adding and configuring a module

**Comment by wgilling** [comment]
pick an existing contrib module (that must work with webform) and config it for those forms that are open to public.

**Comment by elizoller** [comment]
https://www.drupal.org/project/honeypot or https://www.drupal.org/project/captcha might be good to try

**Comment by wgilling** [comment]
I am sure that we could protect all forms, but do we need to? Here is a list of available forms that the honepot module lists:

<img width="755" alt="Screen Shot 2021-05-24 at 9 28 18 AM" src="https://user-images.githubusercontent.com/19391126/119377804-62835580-bc72-11eb-8627-7f17f1e79e78.png">

**Comment by elizoller** [comment]
i was looking for it on the contact and feedback forms since those are publicly available:
http://keep.lib.asu.edu/contact and https://keep.lib.asu.edu/form/feedback
they are both webforms - did it add anything to the webform config?

**Comment by wgilling** [comment]
Yes -- the webforms settings page has an option to protect "All webforms" and each webform's settings page has a "Third party" > "Honeypot" setting to protect that form like:  "Protect Barrett Honors College Submission webform with Honeypot" and "Add time restriction to Barrett Honors College Submission webform ?"

I am not sure what moderation or manual review of form submissions is still possible for any items that have been deemed to contain questionable submissions... or if there is some way to control what qualifies as questionable.

I can eval the "CAPTCHA" module separately.

**Comment by elizoller** [comment]
closed with https://github.com/asulibraries/islandora-repo/pull/400
