### ISSUE TITLE
Add a link to replace the file

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#246]
The route for replacing the file is "/admin/content/files/replace/[fid]" but this isn't linked from anywhere. It'd be good to have it on the media edit page as well as on the admin view of all the files.

**Comment by wgilling** [comment]
Make a custom formatter that will be able to return a file's `fid` value and use this in the link generation to the "Rewrite link" to /admin/content/files/replace/{{ fid }}...
The view is admin/structure/views/view/media_of
