### ISSUE TITLE
Fix alignment of copy link in IIIF box

### ISSUE THREAD

**Issue by dflitner** [asulibraries/islandora-repo#248]
The .js-form-item class is on both the container and the box that the link is in.

The existing style is in form.scss and is:
```
.js-form-item {
  margin-top: 1rem;
}
```

Either of these will fix it:

This one undoes the margin for just this particular element.
```
#iiif_box .js-form-item {
  margin-top: 0;
}
```

This one applies the margin to just this box. I think this one is more dangerous unless we check to be sure it won't affect other forms.
```
#iiif_box.js-form-item {
    margin-top: 1rem;
}
```

**Comment by elizoller** [comment]
a surprise @dflitner sighting! 👋
