### ISSUE TITLE
Weird Image css in Firefox

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#256]
<img width="411" alt="Screen Shot 2020-12-18 at 7 21 43 PM" src="https://user-images.githubusercontent.com/5439169/102678517-55fc4d80-4166-11eb-8a32-7bc4759d2023.png">

**Comment by elizoller** [comment]
@dflitner would you be willing to take this one on?

**Comment by dflitner** [comment]
Could you please link to the record so I can see this live please?

**Comment by elizoller** [comment]
https://prism.lib.asu.edu/items/50

**Comment by dflitner** [comment]
Thank you! I see what's happening. It lines up perfectly when we're logged in because the positioning takes the contextual link region into account. Anon users don't have that so it's off by some amount. I'll get it sorted.

**Comment by elizoller** [comment]
ah, i didn't think of that! i assumed it had to do with chrome v firefox but i'm hardly ever logged in to firefox because that's usually where i'm testing anonymous user views

**Comment by dflitner** [comment]
This fixes it but I wouldn't plop this in without some extra specificity or double-checking. I'm not sure what all are views on the site vs direct queries so it might muck up something else though postion: relative is fairly harmless on its own.
`.views-element-container {
    position: relative;
}`

The arrow is positioned absolutely based on the parent container. When there's contextual links, the parent container has position: relative on it so this duplicates that behavior.

**Comment by dflitner** [comment]
That's the easiest way to make it look the same for both types of users. Otherwise, you could reposition the arrow for non-editors and have a separate rule for .contextual-region .expand-image that undoes that positioning.

**Comment by elizoller** [comment]
ok, thanks debbie. i'll give it a try.
