### ISSUE TITLE
Action to create a Digital Object in Archivesspace

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#266]
We will need an action for PRISM that does two things
1. creates a Digital Object in Archivesspace
2. updates the associated archival object in archivesspace with the link to that newly created digital object from step 1

The "source" field on the repository item would link us to the appropriate archival object in islandora - allowing us to know which archival object to update in step 2.

**Comment by elizoller** [comment]
The only remaining task for this is to have the repository ID dynamically pulled instead of hard-coded.
My thinking is that we can traverse up to the archival resource and get the repository it is connected to (requires adding the id of the repository to the repository content type

**Comment by seth-shaw-asu** [comment]
Resolved with https://github.com/asulibraries/islandora-repo/pull/648
