### ISSUE TITLE
Migration of the automated Graduate College ETDs application

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#28]

**Comment by elizoller** [comment]
This is on hold until discussion around reworking the ETD workflow is complete

**Comment by elizoller** [comment]
this is on hold regarding the above still - requires discussion around ETD workflow

**Comment by elizoller** [comment]
pay special attention to special characters https://repository.asu.edu/items/29820 / https://search-proquest-com.ezproxy1.lib.asu.edu/docview/1680586611/abstract/9A57DB3B289A4B54PQ/4?accountid=4485

**Comment by wgilling** [comment]
Pending meeting discussion about this collection between Dan, Stacey, Joe, and Eli.

**Comment by elizoller** [comment]
the goal for this will be to recreate the functionality of processing proquest ZIPs into KEEP before August 1st so that the process can run on a cron on August 1st straight into KEEP
we currently run the process on a cron on the legacy system on the 1st of the month at 6am on the following months: feb, apr, jun, aug, oct, dec

we will be discontinuing the creation of a MARC record.

**Comment by elizoller** [comment]
this might be a helpful read https://evolvingweb.ca/blog/writing-custom-migration-source-plugin-drupal-8

**Comment by elizoller** [comment]
big thanks to @scottythered for overhauling the etdload python library to have it use drush commands instead of the legacy system API and changing the data models out.
