### ISSUE TITLE
MODS XML partially broken

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#288]
MODS is broken on some objects: https://prism.lib.asu.edu/items/165

**Comment by wgilling** [comment]
going to run the p_c251_node to get the node metadata for testing this in my VM.

**Comment by wgilling** [comment]
I was having the error on ALL content (not just one node)... but this config change seems to make it work again in my VM for the rest.resource.entity.node.yml in the GET section:
```
supported_formats:
    - jsonld
    - json
+   - mods
```

**Comment by wgilling** [comment]
The config for this was missing and this was what fixes it. The updated config file is being added to the `develop` branch for config/sync.

**Comment by elizoller** [comment]
config fix: https://github.com/asulibraries/islandora-repo/commit/c99bbcb62851cd403d07263a59d2fa69e9fcb602
