### ISSUE TITLE
Scroll left/right on mobile

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#297]
You can scroll left/right on mobile when you shouldn't be able to

**Comment by elizoller** [comment]
@dflitner do you know anything about this one? i looked into it briefly and didn't see an obvious fix. i did notice on the other d8 site running the new header and suspect its related to that.

**Comment by dflitner** [comment]
The College's site actually does it a couple of breakpoints. I'll see if I can figure out the problem.

**Comment by dflitner** [comment]
Ok, I think I've got it sorted. I removed the margins on the footer's .row classes at the medium breakpoint. I'll report it to the Unity team and if they get a better fix in, I'll re-roll the module to match.
https://github.com/asulibraries/unity_header/commit/057d08bb29cd2543c67a880d09564a2a9802add9

**Comment by dflitner** [comment]
It doesn't happen in Storybook but I'm not sure if that's due to Storybook or our funky theme.

**Comment by elizoller** [comment]
@dflitner YAY!!!!
fixed with 856844ea2f25b0d8239c7f8f75548c2ddfaaad1c
