### ISSUE TITLE
Add authority URI field to the Title taxonomy vocab

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#300]
After trying to code for MODS import/update on the <subject><titleInfo> elements, the difference between this field and others like Person, Corporation, etc. we asked Alex and determined that the Title taxonomy should have an authority URI.

Add a "Authority Sources" (field_authority_link) field to the "Title" taxonomy http://localhost:8000/admin/structure/taxonomy/manage/titles/overview/fields that would be the same as it is in http://localhost:8000/admin/structure/taxonomy/manage/person/overview/fields

This is a prerequisite for Issue #13 since the import/update migration script will need to populate this taxonomy term field.

**Comment by wgilling** [comment]
I have used these values in the "Authority sources" selectors:

> din1430|Key Title nach DIN 1430 (Berlin: Beuth)
> din1502|Regeln für das Kürzen von Wörtern in Titeln und für das Kürzen der Titel von Veröffentlichungen: DIN 1502 (Berlin; Köln: Beuth)
> dnlm|National Library of Medicine Locatorplus (Bethesda, MD: National Library of Medicine)
> hlasja|HLAS journal abbreviations (Washington, DC: Library of Congress, Hispanic Division
> inisaljt|INIS: authority list for journal titles
> issnkey|Abbreviated key titles External Link
> other|Other

**Comment by elizoller** [comment]
closed with #301
