### ISSUE TITLE
OAI-PMH endpoint

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#31]
likely most of the way there with drupal oai module and islandora_oai. how will oai handle complex objects (will it need to be filtered on objects which do not have any children?) also OAI implementation is limited to listRecords with oai_dc, no set implementation, no mods implementation, no listverbs, etc

**Comment by wgilling** [comment]
there is a taxonomy term for the OAI set -- 
1. this value needs to be populated per item
2. the OAI_PMH view (clone it) should be filtering on these set identifiers

ListRecords -- must take a parameter for which set identifier to use
ListSets

**Comment by elizoller** [comment]
ListSets is here: http://localhost:8000/oai/request?verb=ListSets
ListRecords is here: http://localhost:8000/oai/request?verb=ListRecords&metadataPrefix=oai_dc

**Comment by elizoller** [comment]
module: https://www.drupal.org/project/rest_oai_pmh

**Comment by elizoller** [comment]
two sets that i know of
- one for research output (harvested by Share)
- one for primo (harvested by Alma)

**Comment by elizoller** [comment]
we think to make this simpler and play nicer with the module (which is built to handle a contextual filter for sets), we will add two fields
- oai set on the asu repo item (have this pull from the parent collection field_member_of)
- a boolean field on the asu repo item to flag a thing is a child of a complex object

**Comment by wgilling** [comment]
would this field also be updated in the asu_default_fields_node_insert hook?

- oai set on the asu repo item (have this pull from the parent collection field_member_of)

**Comment by elizoller** [comment]
already done: https://github.com/asulibraries/islandora-repo/blob/develop/web/modules/custom/asu_default_fields/asu_default_fields.module#L149

**Comment by wgilling** [comment]
The code that is setting each object's "field_oai_set" value should be moved to presave hook and apply on updates and inserts. This should also implement something to handle when a collection node field_oai_set value changes - so that it propagates to all of the collection children.

**Comment by elizoller** [comment]
i am concerned about automatically having a collection save iterate through its children and update them.it could be extremely costly.

**Comment by wgilling** [comment]
good point on how that could be problematic although it seems that this action NEEDS TO eventually happen if a collection's field_oai_set is changed -- would it be possible to prompt the user to update all nodes, or update during overnight CRON or something else?

**Comment by wgilling** [comment]
It seems that dc.identifier holds the value of the object's node->id() value as well as the full handle URL but I get errors when I try to query for the specific record.

`<error code="idDoesNotExist">The value of the identifier argument is unknown or illegal in this repository.</error>`

Yet, when I query for ListIdentifiers, the output of one of the identifiers is:
`<identifier>oai:localhost:node-4</identifier>`, so ?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:localhost:node-4 yields that single record. Yay!

The verbs and additional arguments that may be supported.
*?verb=Identify
*?verb=ListMetadataFormats
*?verb=ListIdentifiers&metadataPrefix=oai_dc
*?verb=ListRecords&metadataPrefix=oai_dc
*?verb=GetRecord&metadataPrefix=oai_dc&identifier={???}

**Comment by elizoller** [comment]
you've got the right pattern for getting a single record by identifier, example: https://keep.lib.asu.edu/oai/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:keep.lib.asu.edu:node-11 
and yes dc:identifier is configured to hold the handle as well - that's the specific mapping to DC

**Comment by elizoller** [comment]
sorry was there a question in there that i'm missing?
