### ISSUE TITLE
MODS XML export errors in the log

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#326]
look at https://keep.lib.asu.edu/items/276?_format=mods and then check the dblog
produces several errors

**Comment by wgilling** [comment]
while investigating the fixes to the MODS structure, several things about our resulting MODS export (as well as the import parsing for the relevant elements) are not according to MODS 3.3 schema. These are:

<name> element nameType allowed values does not include "person" but "personal"

The title element should not have any attributes, but the supplied value is embedded into it like:
```
<titleInfo>
 <title supplied="0">Investigating Systematic Reviews Outside Health Sciences</title>
 <nonSort> </nonSort>
 <subTitle/>
</titleInfo>
```

Another thing is that the name element needs to have a <role> wrapper around the roleTerm bit/s...
`<name type="personal"><roleTerm type="code">ctb</roleTerm><namePart>Pardon, Kevin</namePart></name>
`

Genre should not have a valueURI attribute, but it should be "authority".

**Comment by elizoller** [comment]
1. yes, supplied is a valid attribute on titleInfo, not on title, so that'll need to be moved up https://www.loc.gov/standards/mods/userguide/attributes.html#supplied
this may be as simple as moving the`@supplied` up in the mods mapping yml like
```
field_title:
  '_top': titleInfo
  '@supplied': field_supplied #todo map to yes/no
  title:
    '#': field_main_title
  nonSort: field_nonsort
  subTitle: field_subtitle
```
but it would need to be mapped to yes/no instead of 1/0
2. right, role needs to wrap roleterm like. `<role><roleTerm>ctb</roleTerm></role>`
this might work for this:
```
field_linked_agent:
  '_top': name
  '@type': bundle
  role:
    roleTerm:
      '@type': 'code'
      '#': rel_type
  namePart: name
```
3. genre has a valueURI attribute -  https://www.loc.gov/standards/mods/userguide/attributes.html#valueURI

**Comment by wgilling** [comment]
The structure for nesting two nodes deep as for the role/roleTerm does not get through the bottom part of the `get_field_values` method. It is not allowed to pass `$sub_cv` into the recursive method AS AN ARRAY.

```
foreach ($cv as $sub_ck => $sub_cv) {
  if ($sub_cv == "rel_type") {
    $sub_cv = $rel_type;
  }
  if (is_array($val)) {
    $temp_val = $data;
  }
  else {
    $temp_val = $val;
  }
  if (is_array($sub_cv)) {
    $arr_cv = $sub_cv;
  }
  $field_arr[$ck][$sub_ck] = self::get_field_values($temp_val, $sub_cv, $sub_ck);
}
```

**Comment by elizoller** [comment]
specifically because of these lines? 
```
  if (is_array($val)) {
    $temp_val = $data;
  }
 ```

**Comment by wgilling** [comment]
I am seeing that the second parameter that is being sent into get_field_values can not be an array and $sub_cv is an array when the structure of the asu_mods.asu_repository_item is set :
```
field_linked_agent:
  '_top': name
  '@type': bundle
  role:
    roleTerm:
      '@type': 'code'
      '#': rel_type
  namePart: name
```
Does role or roleTerm need an "#" entry - or should the values that it is iterating with `foreach ($cv as $sub_ck => $sub_cv) {...}` not be sub-arrays

**Comment by wgilling** [comment]
changing part of the ModsEncoder to allow the nested `role/roleTerm` elements:
```
  if (is_array($sub_cv)) {
    $arr_cv = $sub_cv;
    array_pop($sub_cv);
  }
  $field_arr[$ck][$sub_ck] = self::get_field_values($temp_val, $sub_cv, $sub_ck);
```

**Comment by elizoller** [comment]
oooh did you get it? 🧙‍♀️

**Comment by wgilling** [comment]
Most of the MODS validation issues have been addressed -- physicalDescription is legal as it is, but it seems that it should be wrapped in only one top level element.

In the code, recordInfo is only created once, but multiple fields are being saved under the recordInfo array element
```
          foreach ($complex_data as $cp) {
            if (is_array($cp)) {
              if ($top_level_elem == "recordInfo" || $top_level_elem == "originInfo") {
                foreach ($cp as $kk => $vv) {
                  $new_data[$top_level_elem][0][$kk] = $vv;
                }
              }
```

I attempted to try handling the physicalDescription like this:
```
          $physicalDescriptions = 0; # initialize before the loop
          foreach ($complex_data as $cp) {
            ...
                if ($top_level_elem == "physicalDescription") {
                  $new_data[$top_level_elem][$physicalDescriptions] = [
                    '#' => [
                      'extent' => [
                        '#' => array_values($cp)[0]
                      ]
                    ],
                  ];
                  $physicalDescriptions++;
                } else {
                  $new_data[$top_level_elem][] = [
                    '#' => $cp,
                  ];
                }
```

**Comment by wgilling** [comment]
Strike that bit about the physicalDescription since it is legal and xpath would pull multiple values regardless.

All of the warnings have been addressed as well as the MODS validation issues that were discovered.

**Comment by wgilling** [comment]
Added a function that "fixes" any data elements that have a value of an empty array - replacing that with a blank string. All notifications should be gone.

**Comment by elizoller** [comment]
closed with https://github.com/asulibraries/islandora-repo/pull/365
