### ISSUE TITLE
Admin toolbar gone for search results pages

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#329]
At least, this impacts the search results page like http://localhost:8000/search?search_api_fulltext=data&sort_by=search_api_relevance&items_per_page=10 when we are logged in as admin.

This is not an issue that impacts the end-user, so it isn't the highest priority yet something underlying might be broken about our HTML.

**Comment by wgilling** [comment]
this may or may not be related to the code behind what this specific GET parameter being populated, but I have noticed that the toolbar is gone when `search_api_fulltext=[anything at all]`

**Comment by wgilling** [comment]
didn't mean to click the "Close issue" button -- my aim was way off.

**Comment by wgilling** [comment]
there is a small possibility that the updated theme for WS2.0 may magically fix this issue, and it is only an inconvenience to us while we are on the search page.

**Comment by elizoller** [comment]
@wgilling this isn't an issue on my local or keep or prism anymore so i'm closing it
