### ISSUE TITLE
Display for objects with no files

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#331]
we should define a model and corresponding view mode for items that do not have any media/fiels
it should do things like
- not have an explore this item sidebar block
- not display a download count

**Comment by wgilling** [comment]
This will need to use the same logic as 4e7ca00 does in the templates for each content type:  asu-image, asu-document, asu-audio, asu-video

**Comment by wgilling** [comment]
This issue is resolved with https://github.com/asulibraries/islandora-repo/commit/2e95b397a9239e59299cb740dea9d2bd9b0dc96b on the develop branch
