### ISSUE TITLE
MODS validation errors

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#345]
The MODS that is created still has several little issues with the validation:

> Cvc-enumeration-valid: Value 'corporate_body' Is Not Facet-valid With Respect To Enumeration '[personal, Corporate, Conference, Family]'. It Must Be A Value From The Enumeration., Line '12', Column '61'.
> Cvc-attribute.3: The Value 'corporate_body' Of Attribute 'type' On Element 'name' Is Not Valid With Respect To Its Type, '#AnonType_typenameDefinition'., Line '12', Column '61'.
> Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'roleTerm'. One Of '{"http://www.loc.gov/mods/v3":namePart, "http://www.loc.gov/mods/v3":displayForm, "http://www.loc.gov/mods/v3":affiliation, "http://www.loc.gov/mods/v3":role, "http://www.loc.gov/mods/v3":description, "http://www.loc.gov/mods/v3":nameIdentifier, "http://www.loc.gov/mods/v3":alternativeName, "http://www.loc.gov/mods/v3":etal}' Is Expected., Line '12', Column '83'.
> Cvc-complex-type.3.2.2: Attribute 'src' Is Not Allowed To Appear In Element 'recordIdentifier'., Line '12', Column '7

**Comment by elizoller** [comment]
this is replaced by #364
