### ISSUE TITLE
Admin toolbox - legacy item link, display model, export CSV / MODS

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#352]
These suggestions are not derived from any specific use cases, but stem from discussions... It may be really nice to display some of these links to Metadata managers as well.

a link to the legacy item (if it can be linked, else show some text that indicates that the legacy item could not be linked)
individual links to download CSV or MODS (even though these are at the bottom of the page) (???)
display the islandora_model of the asu_repository_item object

**Comment by elizoller** [comment]
added model and fedora uri in https://github.com/asulibraries/islandora-repo/commit/aef84e092b93f68c3e70a8233c06b6529b968c75#diff-328eaef56e76a3cfb1ee46a27de5bd5626cca016d09475830368bc9bc0a5edfc

**Comment by wgilling** [comment]
there is a separate commit in the csv_export_333 branch that displays a link for Download CSV in the admin toolbox for collections and items -- as well as a "Download CSV" link at the top of a search page.  https://github.com/asulibraries/islandora-repo/commit/b5be055b9e28a05b34648ecfa64981f0716145f1 "added link to admin toolbox and on search form to download CSV, added placeholder formatter for importing Geolocation field values, importing Level of Coding, Statment of Responsibility, Complex object child, Issuance, Frequency, Edition, Open access, Peer-reviewed, Title Subject, Temporal Subject, possibly more for #333" (I know that's almost the longest commit memo).

This can likely be closed when csv_export_333 is merged.

**Comment by wgilling** [comment]
The legacy link would need to calculated based on whether or not the field_pid is populated. If it is populated, the link would simply be: 
repository.asu.edu/items/{node.field_pid} 

If the first character of field_pid is "a", then it represents an attachment (complex object child usually) and the link above would not work.

**Comment by wgilling** [comment]
Who would get to see the legacy link? I am going to code it the same as the CSV link (Admins and Metadata managers) and it can be changed if needed.

**Comment by elizoller** [comment]
sounds good
