### ISSUE TITLE
Give content owners the ability to reorder children objects

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#354]
the reorder children view needs to be added to the admin toolbox and have the breadcrumbs adjusting to include the item.

**Comment by elizoller** [comment]
It'd be nice if it had the item sidebar too

**Comment by elizoller** [comment]
@wgilling want to tackle this one?

**Comment by wgilling** [comment]
there is an existing "reorder children" view... make link in appropriate place for the correct users and voila.
