### ISSUE TITLE
CSV import/export bugs

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#357]
When a field_title value of an asu_repository_item is exported in a CSV, the exported value converts the characters into their html entities -- for example, a character such as < or > is being exported as `&lt;` or `&gt;`.

The Date Created EDTF field is not actually being exported and the System Date field is actually being exported instead. This will need to be adjusted so that the Date Created is exported and imported.

**Comment by wgilling** [comment]
There is a commit currently in the csv_export_333 branch that handles the decoding of this value in the meanwhile.

**Comment by elizoller** [comment]
This one is still eluding me.

**Comment by elizoller** [comment]
closed with #387
