### ISSUE TITLE
broken links in the Content Digest emailing

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#371]
The view http://localhost:8000/admin/structure/views/view/differences/edit/page_2 links that do not function in any content digest emailing:

- the item title
- the content author
- "Next page ››"

For the "Next page ››", this link should navigate to the actual second page of the digest for that day... however - since this report is based off of a "prior 1-day period" that link would could not be relevant if it is clicked on a subsequent day.

The links should function and the view will need to be made to operate off of a date - and the page defaults to the prior 1 day period if the parameter is not supplied.

**Comment by elizoller** [comment]
is it actually paginated? or is it set to a hard limit on how many things can show up in the email? just asking because there are some days when 50000 things get added

**Comment by wgilling** [comment]
Yes - it is using the mini pager with 50 items limit.

At the bottom of the emailing from yesterday, I see:
> Pagination
> 
> Page 1
> Next page ››

The "Next page ››" link makes a sound when I click it and when I copy it has a value of "applewebdata://55EB0758-0A64-4ED1-B015-8968CD5FE387/home?page=1"

**Comment by elizoller** [comment]
closed with #375
