### ISSUE TITLE
Clicking on Preview when editing an ASU Repository Item throws an error

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#374]
The error message is:

> Error: Call to a member function hasField() on null in Drupal\asu_item_extras\Plugin\Block\AboutThisItemBlock->build() (line 107 of /var/www/html/drupal/web/modules/custom/asu_item_extras/src/Plugin/Block/AboutThisItemBlock.php)

**Comment by elizoller** [comment]
@wgilling is this still an issue? i don't think that we're showing the sidebar on the edit page?
