### ISSUE TITLE
Typed Identifier field should sometimes display values as links

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#381]
DOIs should be presented as links automatically on output (a theming layer issue since we can't actually store the data like that)

**Comment by wgilling** [comment]
For example, the item https://keep.lib.asu.edu/items/496 is displaying:
**Identifier**
Digital object identifier : 10.7554/eLife.65066

After the enhancment, it would convert the "10.7554/eLife.65066" part into a link to point to the DOI.

This should only be done if the value is not a link already. If the doi value contained http or something use that link, and if not then prepend the https://doi.org/

**Comment by wgilling** [comment]
Make a custom twig template for the typed-identifier paragraph type. paragraph--typed-identifier.html.twig
