### ISSUE TITLE
Schedules for patching (at a variety of levels)

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#39]

**Comment by elizoller** [comment]
Deirdre has added the 3 EC2 instances running on AWS Dev to the monthly Linux patching schedule. Still need to determine schedule and process for updating Drupal Core and contributed modules.

**Comment by elizoller** [comment]
Note: That Kirk reminded us if we need any specific libraries locked, we need to notify them in advance so it doesn't get updated during their patching.

**Comment by elizoller** [comment]
- Security patches should be done ASAP (to Drupal Core, contributed modules)
- Drupal core updates and contributed module updates (non-security) should be reviewed/attempted on a monthly basis and shouldn't take precedence over any major MVP milestones
- Updates should be tested locally in development environments, pushed and tested in a sandbox environment, before being deployed to production
- For major updates, external (non-developer) stakeholder testers would be preferred
- All changes/deploys to production must be approved with a change management request.

**Comment by elizoller** [comment]
Would be nice if had a module that sent an email or notification to notify us that there are updates to be performed

**Comment by dflitner** [comment]
This is default Drupal behavior. See the config page at /admin/reports/updates/settings

I don't know if this will also track the Islandora modules. They have their own repos but I'm not sure if it checks non-Drupal git repositories.

**Comment by elizoller** [comment]
I'm guessing that would work for drupal.org hosted modules but I'm guessing that it doesn't like check packagist/composer for new versions which is where the islandora modules would come in. But we can try it out (once I get the SMTP setup)

**Comment by elizoller** [comment]
Propose implementing ELB and putting a splash page there for when things are down.

**Comment by dflitner** [comment]
Sorry, what’s ELB?

**Comment by elizoller** [comment]
Elastic Load Balancer

**Comment by elizoller** [comment]
ELB provisioning added with https://github.com/asulibraries/claw-playbook/commit/f728015c4c42083508d776bbd4bb644ee9247bce

**Comment by elizoller** [comment]
Suggested methodology for handing downtime static pages would be setting up a cloudfront distribution 
- Goes in front of the load balancer
- Recommends creating an S3 bucket with static web pages
- Then use a Cloudfront distribution with two origins: your app and your s3 bucket
- Configure in cloudfront the failovers from your app into your s3
- Can also serve pages through Lambda instead of with S3

**Comment by elizoller** [comment]
Eli to do: Move documentation about maintenance to outside github issue. Add S3 bucket for static pages and add pages for 500 and 503. Then ask Deirdre to point cloudfront to the load balancer and the new s3 for static pages.

**Comment by elizoller** [comment]
We've completed what we are going to ahead of MVP launch. We will add cloudfront and static downtime pages, with CDN module for advanced caching at a later date.

**Comment by elizoller** [comment]
will address remaining tasks in #225
