### ISSUE TITLE
Bug in DownloadsBlock when no media on items

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#404]
When there is an item that has not had any media added to it, the DownloadsBlock throws a fatal error. This is:

> Notice: Undefined offset: 0 in Drupal\asu_item_extras\Plugin\Block\DownloadsBlock->build() (line 130 of /var/www/html/drupal/web/modules/custom/asu_item_extras/src/Plugin/Block/DownloadsBlock.php)

The code should check that there are entities before trying to test the access on that...

Also, the two "access variables" are not used at all and I am. not sure if it was an oversight or that the access logic happens for the block build during that line - and thereby effect the block's visibility.

**Comment by wgilling** [comment]
When @elizoller gets back, discuss the two access variables that are not used in the code. These are `$of_access` and `$sf_access`.

**Comment by elizoller** [comment]
@wgilling can you verify that the recent commit fixes this for you?

**Comment by wgilling** [comment]
> @wgilling can you verify that the recent commit fixes this for you?

Yes, the item that had no media on it displays fine now with the latest code.

**Comment by elizoller** [comment]
fixed with 
06970fa
