### ISSUE TITLE
Associate the feedback form with items and collections

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#427]
This used to work before we had so many entities in the system that webform basically barfs when you try to use an entity reference of any kind. so the work around would be to store integers for the node ids for collections and items and look up the nodes dynamically when necessary (ie. on the webform view and on the webform submit most likely).
this is a follow up to #349

**Comment by wgilling** [comment]
From our Slack conversation - Eli wrote:

> it has to do with webforms. basically the feedback form had entity fields that prepopulated the item and the collection whenever the feedback link was clicked. but webforms kept crashing with any entity reference on it on production due to the number of entities. it tried doing things like changing it from an autocomplete to a dropdown or any variety of configuration there was available and nothing worked. so i eventually removed the fields entirely because no one could use the feedback form. i'd like to add the fields back. my suggestion would be to use simple text or integer field for the item nid (if its from an item page) and the collection nid and then have it look up the item and collection nids and populate the titles and URLs to those things. it'd be nice if the email had the id, title, and URL. as a bonus, it'd be great if it displayed to the user when they are filling out the form too (so they know what item/collection they are submitting about). i think there are several ways to do this. you could do the look up sort of on the fly in the form view as well as the submission process and load the nodes then. or you could load the nodes only in the form view and save the titles and links as hidden fields in the webform that then the submission process would read the field values instead of doing a second lookup.
> this will involve modifications to the webform configuration as well as code changes.
> i think you modify the form with a form alter hook. if you decide to go the route of modifying the submission process (instead of storing the titles and links in webform fields) then you'll need a custom webform submission handler of which we have few examples in our code - the self deposit code for example

**Comment by wgilling** [comment]
I did not get the email because I have yet to. configure SMTP but I ran a test submission from a collection page and it seems to indicate that the feedback was submitted for *(to) collection 3 which is named "test collection".
![Screen Shot 2021-07-15 at 9 05 34 AM](https://user-images.githubusercontent.com/19391126/125820475-719f60c7-a99f-4a7a-919a-79c3da141359.png)

**Comment by wgilling** [comment]
I am inferring that the webform needs to display the item or collection when the user is making the submission, but am confused as to why it would need a select box for all items in a collection.

Testing the Feedback from an item page -- it has been submitted to the item (not the collection) and the title of that item is "test audio item". Though this submission's "Submission URI" value contains the collection as the collection parameter (=3): "/form/feedback?source_entity_type=node&source_entity_id=8&item=8&collection=3&primary_element=item"

![Screen Shot 2021-07-15 at 9 11 40 AM](https://user-images.githubusercontent.com/19391126/125821314-86661c69-7ec3-49e9-af91-a42741e46bc7.png)

**Comment by wgilling** [comment]
The emailing that is sent for the webform's submissions displays the title of the content for which the feedback is submitted.

The current code is simply displaying either the item or collection values as a read-only integer field this will need to be handled in a form alter routine in asu_webform_extras and will render as links to this content in the  display and the email.

**Comment by wgilling** [comment]
The newest approach will set a "feedbackon" Basic HTML field to render the links to item and collection and the email template will need to also handle this explicitly since webform does not treat the altered field value as something that it will output when using the token [webform_submission:values] or explicitly by [webform_submission:values:feedbackon:raw].
