### ISSUE TITLE
Support the "paged content" model

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#437]
We have discovered several items, such as https://prism.lib.asu.edu/items/62728, which are documents/items where each page is a separate item. The default islandora "paged content" model uses openseadragon to display things like this in a "paged" way. we need to make this work in our system with our viewer controller

**Comment by wgilling** [comment]
Need some changes in the viewer controller to tie it together, add a view mode and twig file for this -- this would use the OpenSeadragon viewer. Configuration of OpenSeadragon in order to make sure it could handle a 300 page book.

**Comment by elizoller** [comment]
mirador + iiif is enabled and all wired in. we only have one test case with the parent set to "paged content" - will need to determine what other objects need this model

**Comment by elizoller** [comment]
I think the technical work is done for this and more a matter of assigning the "paged content" model so i'll close this from the code perspective
