### ISSUE TITLE
Add a link in the admin toolbar to manage the users of a collection

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#438]
The admin toolbar on collection pages should include a link to managing the users associated with the collection. The difficulty is that it'll either need to lookup the collection's group membership or by the title of the group.

**Comment by wgilling** [comment]
Would this idea of looking up a collection's group membership be similar to the helper function of the ASUAdminToolboxBlock.php canAddChild()?

```
  /**
   * Checks whether the current user can add a child to the collection.
   *
   * @return bool
   *   Returns whether the user can add a child to the object.
   */
  public function canAddChild() {
    $grps = $this->groupMembershipLoader->loadByUser($this->currentUser);
    $access = FALSE;
    $plugin_id = 'group_node:asu_repository_item';
    foreach ($grps as $grp) {
      if ($grp) {
        $access |= ($grp->hasPermission("create $plugin_id entity", $this->currentUser));
      }
    }
    return $access;
  }

```

**Comment by elizoller** [comment]
not quite. this is more about the fact that there are group objects for each collection. so you could either look up the group by name - like "Collection x Group" or by membership - groups which this collection node is a member of (although that might get confusing based on sub-collections...)
