### ISSUE TITLE
Export to CSV in search doesn't properly get query URL params

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#452]
When running a search with facets as an admin or metadata manager, you are supposed to get a url to download the CSV of the search but the query parameters are not being parsed correctly.
It results in an error:
```
Notice: Array to string conversion in asu_search_views_pre_render() (line 152 of /var/www/html/drupal/web/modules/custom/asu_search/asu_search.module)
```
and is due to 
```
        $query_string_parts[] = $query_key . '=' . $query_value;
```
(line 152) $query_value is actually an array.

**Comment by wgilling** [comment]
I do not see a link to download CSV export of faceted search results and I am logged in as Administrator. Has this been suppressed as a hotfix?

**Comment by wgilling** [comment]
the latest version of this code seems to deal with the problem of the $query_value being an array (commit b5be055b9 from 3/29/2021):
```
      $query_string_parts = [];
      foreach ($query_parts as $query_key => $query_value) {
        $query_string_parts[] = $query_key . '=' . $query_value;
      }
      $query_string = implode("&", $query_string_parts);
      $view->header['area_1']->options['content']['value'] .= ' | ' . "<a href='" .
        $current_url . "/csv?" . $query_string . "' target='_blank'>Download CSV</a> &nbsp;" .
        "<a href='" . $current_url . "/csv?" . $query_string . " target='_blank'><i class='fas fa-file-export'></i></a>";
```

**Comment by elizoller** [comment]
this is still a problem. ie here: https://keep.lib.asu.edu/search?f%5B0%5D=member_of%3AFaculty%20and%20Staff&search_api_fulltext=arizona and click the download CSV button (you can see in the link that its got the word Array literally in it)

**Comment by elizoller** [comment]
ie https://keep.lib.asu.edu/search/csv?search_api_fulltext=arizona&f=Array
