### ISSUE TITLE
Accommodate non-ASU affiliate access

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#46]

**Comment by elizoller** [comment]
We could also potentially implement like a temporary/expiring link to contribute to this.

**Comment by elizoller** [comment]
We'd like to try to avoid per-item node permissions, but if we need it, it might be possible with https://www.drupal.org/project/nodeaccess

**Comment by wgilling** [comment]
potential module to expire roles on user accounts: https://www.drupal.org/project/role_expire

**Comment by elizoller** [comment]
7b0471ef adds the ability to let a user log in NOT through CAS
