### ISSUE TITLE
Bring back the comma in the search result count

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#470]
In order to bring back the collections results in the view header, i had to undo the change that brought in the formatted total row count to add the comma. in the essence of time, i just removed the logic that hid the view header and added in the formatted row count. but we should be able to do both - have a view header and a formatted row count. in theory.
here is the change i had made: https://github.com/asulibraries/islandora-repo/commit/fd2ac0963433321e59fe3523e9daa825920345d6#diff-46775c9de8f155eff12215782bdcc407cc255fc1596de7cff62ca849cb99d9de

**Comment by wgilling** [comment]
The logic that was in the template actually removed the view header when the template variable was present, causing the matching collections results to disappear. Need to refactor in a way that does not work that way.
