### ISSUE TITLE
CAS authentication

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#48]
hoping we'll be able to use https://www.drupal.org/project/cas but will need to build an additional integration which checks for whether or not the user is in_headcount in authprod. if we're ok with external users then maybe we should just flag them as external and have a policy that purges them after one year or not logging in - or something like that. not sure what is involved with getting our domains registered with UTO to allow CAS auth

**Comment by elizoller** [comment]
Finally got cas sorted in staging. Required private ip only on ec2 and application load balancer in public subnet. Installed CAS attributes but doesn’t appear to get us any more useful data. With just CAS we get asurite and email address. I think first and last name would be a nice addition @dflitner - I think you mentioned using ldap?

**Comment by dflitner** [comment]
Yes, we use LDAP to get more information about users on the D7 site. However, when I tried to hook it up in D8, something didn't work. I don't remember what the issue was at the moment. I will try to recreate it and report back.

**Comment by elizoller** [comment]
Ok, i've decided to make a different ticket for LDAP since its another can of worms.

**Comment by elizoller** [comment]
closed with de2626dfc01fabc44ce58f01d08e39c8f77e92ee 0b6535e9ec9f48eac0dbcdc1561973aa64d37004 f887dc5de0a56368657fdd62276646d920e57d2c d0f7bdfbe3777f6a5dfde65939e36db15bd6e90e 7b03b66d3aa43132391a80f05dd48642c2c650ee
