### ISSUE TITLE
On production sites, uninstall Search API Solr Search Defaults

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#485]
There are possibly other modules that really are not intended for our production sites. While troubleshooting an unrelated solr issue I was seeing, I noticed that this module is installed by default and the message on the Extend page says:

> After installation it is recommended to uninstall this module again for performance reasons. The provided configuration will not be removed.

This module appears to be enabled on KEEP https://keep.lib.asu.edu/admin/modules as well as on PRISM https://prism.lib.asu.edu/admin/modules

**Comment by elizoller** [comment]
sounds good - if you uninstall in your local does everything still work ok?

**Comment by wgilling** [comment]
It did not create any issues as of yet, but I have not hammered on a lot yet... so I will keep it uninstalled and see if any issues come up. I doubt that removing it causes any issues because the module README states that this module can safely be removed because it does not remove any configs that it put into place in order to set up Solr easier.

**Comment by elizoller** [comment]
done.
