### ISSUE TITLE
ASUItemIsPartOf block runs on search results page

### ISSUE THREAD

**Issue by wgilling** [asulibraries/islandora-repo#490]
There are two separate blocks related to showing the parents of an item - via the `field_member_of` relationship... one that is used for search results and another that is used only on item overview pages. While debugging some code on the search page, I could see that the code for ASUItemIsPartOf was executing when ONLY the ASUSearchItemIsPartOf should have been running.

For reference, the ASUItemIsPartOf block is created in the various node--asu-repository-item--asu-{model-view}.html.twig and it passes the current node in as a parameter. For example, the node--asu-repository-item--asu-document.html.twig has this line:

      {{ drupal_block('asu_item_is_part_of', {'node': node}) }}

While the search results node--asu-repository-item--search-result.html.twig have this line:

        {{ drupal_block('asu_search_item_is_part_of', {'paragraph': par_title, 'parent_node_id': parent.id }) }}

**Comment by elizoller** [comment]
it was unnecessarily running due to 8cbcd3ec

**Comment by elizoller** [comment]
8cbcd3ec
