### ISSUE TITLE
Extract and store technical metadata via FITS on media/files

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#50]
pending merging of FITS with crayfits

**Comment by elizoller** [comment]
FITS is now shipped with Islandora and likely won't even require any additional config as of https://github.com/asulibraries/claw-playbook/commit/df649342737f872c3ded4f74db8279ed29c9c324

**Comment by elizoller** [comment]
This just needs to be tested - I see the microservice running and the module enabled in drupal and the context set but when I make a new "original file" media I'm not getting a FITS file.

**Comment by elizoller** [comment]
i verified FITS works (http://10.202.6.138:8000/media/67 but we have to lock islandora_fits to its last known working commit - as mentioned here: https://github.com/Islandora/documentation/issues/1405

**Comment by elizoller** [comment]
Just need to verify the install and locking to this commit

**Comment by wgilling** [comment]
with the claw-playbook code (without running `drupal config:import --directory config/sync`), image object when added as the Media [@type="file"] | (having "Original file" checked) for a TIFF file does create a FITS datastream.

The only part that didn't work as expected was when the Media was attached as [@type="file"] but the Original file" checkbox was not checked the first time [Save] was clicked, it never generated a FITS -- it was resolved by editing the media and uploading a new TIFF file but being sure to ALSO have the "Original file" checkbox checked.

@elizoller, might this be a good issue to bring up with the Islandora 8 call?

**Comment by elizoller** [comment]
Hopefully a user will not have the option to forget to select a media use. The action to trigger FITS creation  after initial object creation is available through the node when you go /admin/content 
I think this can be closed?

**Comment by wgilling** [comment]
agreed
