### ISSUE TITLE
Sticky menu on small screens

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#501]
instead of having the sidebar be below the content on small screens, maybe we would put it in a collapsible/expandable menu

**Comment by dflitner** [comment]
Here is what is in Storybook for sidebars:
https://unity.web.asu.edu/@asu-design-system/bootstrap4-theme/iframe.html?id=atoms-sidebar-examples--sidebar&args=header:false;footer:false;template:1&viewMode=story

**Comment by elizoller** [comment]
oh excellent!

**Comment by elizoller** [comment]
thanks!!
