### ISSUE TITLE
Disaster recovery plan

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#52]

**Comment by wgilling** [comment]
In effect, the act of moving the code and configurations from DEV to STAGE would be a process that would be able to flush out the required steps for deploying the site from a copy.

**Comment by elizoller** [comment]
We could test a full swap over to a new AWS setup (EC2, RDS, S3, etc) by spinning up new ones and then provisioning and copying over existing data (drupal, fedora, etc) to run through a full rebuild with sample data.

**Comment by elizoller** [comment]
Need to think about more scenarios - like what if amazon disappears?

**Comment by elizoller** [comment]
Initial baseline would be a daily backup of databases, storage volumes.

**Comment by elizoller** [comment]
RDS backup issue: https://github.com/asulibraries/islandora-repo/issues/95

**Comment by elizoller** [comment]
S3 lifecycle rules and replication rules do not have complete enough implementation in ansible modules, we this must be done manually in the aws console. lifecycle rule to intelligent tiering and replication rule to equivement bucket in disaster recovery account.

**Comment by elizoller** [comment]
This issue is still pending while we sort out the configuration of the replication rule to push from dev -> disaster recovery

**Comment by elizoller** [comment]
The replication rule has to be done manually through the aws console and cannot be automated via Ansible. It is set up in the staging environment, but will need to be set up in the production environment when deployed there.
