### ISSUE TITLE
Extent (page numbers) from Barrett self-submissions are not mapping to the repo item node

### ISSUE THREAD

**Issue by dflitner** [asulibraries/islandora-repo#544]
Stacey has reported that new submissions on the Barrett form are not getting their page numbers mapped correctly. The extent info is in the submission but not in the final node.

Info from Stacey:

> Eli updated it in January before he left because Meredith had discovered that it was not capturing page numbers for any theses submitted as “complex objects.” Now it looks like there’s a problem and they aren’t showing up at all.
>  
> I viewed some of the recent submissions, and page number is being captured – the form itself seems okay from what I can tell, but it’s not actually taking that value and putting it in the repo record. Not sure if you would have any insights into what is going on.
>  
> Example of a submission today in the repo: https://keep.lib.asu.edu/items/163463/metadata (missing Extent/page numbers)
> \and the submission, which has page numbers: https://keep.lib.asu.edu/admin/structure/webform/manage/barrett_honors_college_submissio/submission/476?destination=/admin/structure/webform/manage/barrett_honors_college_submissio/results/submissions

The commit is https://github.com/asulibraries/islandora-repo/commit/4a3ab3e603091b8953c0edb77dab35b635947f8a and it looks like the extent only gets added to child nodes rather than parent and standalone nodes.
I think line 258 should be `$child == FALSE`.

Trying to get my local up to test this.

**Comment by elizoller** [comment]
sounds right to me to change `$child == FALSE` on line 258

**Comment by dflitner** [comment]
Sorry I didn't realize this would ping you. Just trying to be good about documenting. 

I got a successful `vagrant up` but there's no drupal folder and I can't remember where it's hiding. Just `cd /var/www/html/drupal` isn't working and I seem to remember that being a thing but I might be mixing it up with another setup.

**Comment by elizoller** [comment]
try cloning https://github.com/asulibraries/islandora-repo into the islandora-playbook and then probably destroy and re-up

**Comment by dflitner** [comment]
I was trying to do a "from scratch" install because I was worried about the basebox being out of date. However, I tried with the basebox and it worked so I will start from there for now. I'll dig through our Slack convos and my notes from ages ago and see if I can find info about the "from scratch" install for future reference.
Thanks for responding!

**Comment by elizoller** [comment]
yeah, let me know if you need anything

**Comment by seth-shaw-asu** [comment]
@dflitner, is this still an issue, or can we close it?

**Comment by dflitner** [comment]
I never got a local Islandora instance working to be able to test it or do a commit/pull. It should be a fairly quick fix assuming that is the correct solution.
