### ISSUE TITLE
Taxonomy issue

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#557]
KEEP and PRISM taxonomy issues - the taxonomy pages constantly time out and cannot be accessed.

**Comment by seth-shaw-asu** [comment]
Hitting a gateway timeout on production. Dev didn't have the same issue but also has far fewer taxonomy terms in each vocabulary.

I loaded up the Tags vocabulary on repo-dev with 9k terms and was able to produce the following (trimmed) error:
`FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/drupal/web/core/lib/Drupal/Component/Utility/NestedArray.php on line 73", request: "GET /admin/structure/taxonomy/manage/tags/overview HTTP/1.1", referrer: "/admin/structure/taxonomy"`

This seems consistent with the taxonomy performance issue identified in https://seth-shaw-unlv.github.io/2020-09-07/large_vocab_list_error, but I'll run another test or more to verify.

**Comment by seth-shaw-asu** [comment]
I confirmed the large taxonomy patch works, at least on dev:
```diff
            "drupal/core": {
                "fix for taxo term save": "https://www.drupal.org/files/issues/2020-10-29/2893747-33.patch",
-               "fix for blocks not showing up": "https://www.drupal.org/files/issues/2018-10-27/2997898-21.patch"
+               "fix for blocks not showing up": "https://www.drupal.org/files/issues/2018-10-27/2997898-21.patch",
+               "fix for large taxonomies": "https://www.drupal.org/files/issues/2021-05-26/763380-73.patch"
            },
```
Next step is to apply the patch on production and verify the fix there.

**Comment by seth-shaw-asu** [comment]
Resolved with https://github.com/asulibraries/islandora-repo/commit/5d9828bdb6c359a5a0d8dba6d8afa05160aa1da2
