### ISSUE TITLE
CSS error.

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#558]
When you click on any title of any repository item, the CSS styling for the second line overlaps the black frame just slightly over onto the line above.

**Comment by seth-shaw-asu** [comment]
See https://keep.lib.asu.edu/search?search_api_fulltext=Arizona%20Extreme%20Weather%20and%20Public%20Health:
![Screenshot 2022-08-24 140750](https://user-images.githubusercontent.com/108362375/186523944-4e9d6d9d-1a2b-45f3-a824-77c8ee2aee11.png)
