### ISSUE TITLE
Object deletion error.

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#559]
This empty and broken parent object needs to be deleted, but it's giving the website error message. https://keep.lib.asu.edu/items/167061

**Comment by seth-shaw-asu** [comment]
Associated error message: `InvalidArgumentException: Field field_additional_memberships is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityBase.php).`

Unfortunately, I'm a bit hamstrung in debugging it until `drush php:cli` is working again.

**Comment by seth-shaw-asu** [comment]
Side-note: I purged migrate_run and updated Drush to the latest 10.x release which fixed php:cli.

**Comment by seth-shaw-asu** [comment]
It still isn't clear why the item was refusing to load. However, I simply deleted the record using the command-line interface. No errors were reported and now visiting the URL results in a 404 as expected.
