### ISSUE TITLE
Derivatives once again.

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#562]
These don’t have thumbnails generated from the video like the rest do, and they also say that the file is corrupted when I try to download them: https://keep.lib.asu.edu/items/145913 https://keep.lib.asu.edu/items/146482 https://keep.lib.asu.edu/items/146468 https://keep.lib.asu.edu/items/127169 https://keep.lib.asu.edu/items/127167 https://keep.lib.asu.edu/items/127165

**Comment by seth-shaw-asu** [comment]
It appears that most of these have issues where characters in the filename (such as the `#` in several of them) are causing issues with saving to or retrieving from Fedora.

@merfimcfarland , is it possible you can delete the original media and create a new ones with renamed files with simpler names (limit punctuation to underscores and hyphens). You can put the original file name in the original filename field on the upload form.

Once again, we should consider the transliterate plugin to save ourselves some of this headache moving forward.
