### ISSUE TITLE
Viewer problem.

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#563]
These won't generate viewers for the PDFs:
- https://keep.lib.asu.edu/items/160845
- https://keep.lib.asu.edu/items/160934
- https://keep.lib.asu.edu/items/161092
- https://keep.lib.asu.edu/items/161093
- https://keep.lib.asu.edu/items/161121
- https://keep.lib.asu.edu/items/161169
- https://keep.lib.asu.edu/items/161172
- https://keep.lib.asu.edu/items/161174
- https://keep.lib.asu.edu/items/161206
- https://keep.lib.asu.edu/items/161213
- https://keep.lib.asu.edu/items/161214
- https://keep.lib.asu.edu/items/161215
- https://keep.lib.asu.edu/items/161220
- https://keep.lib.asu.edu/items/161221
- https://keep.lib.asu.edu/items/161222
- https://keep.lib.asu.edu/items/161223
- https://keep.lib.asu.edu/items/161224/members
- https://keep.lib.asu.edu/items/162266
- https://keep.lib.asu.edu/items/162989
- https://keep.lib.asu.edu/items/162990

**Comment by seth-shaw-asu** [comment]
Bugs:
- https://keep.lib.asu.edu/items/160845
    File exists in Fedora by Flysystem is producing the following error during retrieval: `TypeError: stream_copy_to_stream(): Argument #1 ($from) must be of type resource, bool given in stream_copy_to_stream() (line 306 of /var/www/html/drupal/vendor/symfony/http-foundation/BinaryFileResponse.php)`
- https://keep.lib.asu.edu/items/162266
  The original file is empty (zero-length). The upload of the original file probably failed. We need to find an original copy somewhere.

Simply needed thumbnails:
- https://keep.lib.asu.edu/items/160934 (now has a thumbnail but it is a black rectangle)
- https://keep.lib.asu.edu/items/161092
- https://keep.lib.asu.edu/items/161093
- https://keep.lib.asu.edu/items/161121 (now has a thumbnail but it is a black rectangle)
- https://keep.lib.asu.edu/items/161169
- https://keep.lib.asu.edu/items/161172
- https://keep.lib.asu.edu/items/161174 (now has a thumbnail but it is a black rectangle with a little bit of text)
- https://keep.lib.asu.edu/items/161206
- https://keep.lib.asu.edu/items/161213
- https://keep.lib.asu.edu/items/161214  (now has a thumbnail but it is a black rectangle)
- https://keep.lib.asu.edu/items/161215
- https://keep.lib.asu.edu/items/161220  (now has a thumbnail but it is a black rectangle)
- https://keep.lib.asu.edu/items/161221
- https://keep.lib.asu.edu/items/161222  (now has a thumbnail but it is a black rectangle)
- https://keep.lib.asu.edu/items/161223
- https://keep.lib.asu.edu/items/161224/members
- https://keep.lib.asu.edu/items/162989
- https://keep.lib.asu.edu/items/162990

**Comment by seth-shaw-asu** [comment]
Reported the issue with 162266 to repo-ops and opened a new issue for 160845. Closing.
