### ISSUE TITLE
MOV videos should not display the web player

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#567]
I can’t get these to play in KEEP no matter how long I let them load: https://keep.lib.asu.edu/items/127223 https://keep.lib.asu.edu/items/127227 https://keep.lib.asu.edu/items/127228 https://keep.lib.asu.edu/items/127229 https://keep.lib.asu.edu/items/127418 https://keep.lib.asu.edu/items/127213 https://keep.lib.asu.edu/items/127214 https://keep.lib.asu.edu/items/127217 https://keep.lib.asu.edu/items/127218 https://keep.lib.asu.edu/items/127537 https://keep.lib.asu.edu/items/127538 https://keep.lib.asu.edu/items/127489 https://keep.lib.asu.edu/items/127491 https://keep.lib.asu.edu/items/127492 https://keep.lib.asu.edu/items/127493 https://keep.lib.asu.edu/items/127477

**Comment by seth-shaw-asu** [comment]
Browsers don't natively support the MOV for playing. So, two issues: 
1. these videos should have WebM or MP4 service files and, 
3. we shouldn't display the web viewer for videos that aren't supported by browsers, such as MOV.

**Comment by seth-shaw-asu** [comment]
Additional clarification: MOV files should be uploaded as "File" media instead of "Video" media. Video media are those that most browsers can play natively.
