### ISSUE TITLE
More video issues.

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#568]
I can’t get these to play, and there don’t seem to be accessible files anywhere in KEEP. The thumbnails also need generation: https://keep.lib.asu.edu/items/127341 https://keep.lib.asu.edu/items/127342 https://keep.lib.asu.edu/items/126983/members (Black screen issue) https://keep.lib.asu.edu/items/127276 https://keep.lib.asu.edu/items/127307 https://keep.lib.asu.edu/items/127300 https://keep.lib.asu.edu/items/127301 https://keep.lib.asu.edu/items/127302 https://keep.lib.asu.edu/items/127177 https://keep.lib.asu.edu/items/127176 https://keep.lib.asu.edu/items/127184 https://keep.lib.asu.edu/items/127185 https://keep.lib.asu.edu/items/127181 https://keep.lib.asu.edu/items/127282 https://keep.lib.asu.edu/items/127219 https://keep.lib.asu.edu/items/127215 https://keep.lib.asu.edu/items/127122 https://keep.lib.asu.edu/items/127123 https://keep.lib.asu.edu/items/127114 https://keep.lib.asu.edu/items/127122 https://keep.lib.asu.edu/items/127121 https://keep.lib.asu.edu/items/127124 https://keep.lib.asu.edu/items/127125 https://keep.lib.asu.edu/items/127318 https://keep.lib.asu.edu/items/127316 [https://keep.lib.asu.edu/items/127317](https://keep.lib.asu.edu/items/127317https://keep.lib.asu.edu/items/127317) https://keep.lib.asu.edu/items/127315 https://keep.lib.asu.edu/items/127536 https://keep.lib.asu.edu/items/127539 https://keep.lib.asu.edu/items/127064 https://keep.lib.asu.edu/items/127067 https://keep.lib.asu.edu/items/127431 https://keep.lib.asu.edu/items/127476 https://keep.lib.asu.edu/items/127046 https://keep.lib.asu.edu/items/127047 https://keep.lib.asu.edu/items/127052 https://keep.lib.asu.edu/items/127053 https://keep.lib.asu.edu/items/127048

**Comment by seth-shaw-asu** [comment]
Many of these suffer from one or both of #508 and #567.

In most cases video derivatives should be created (such as with #567), although may not be able to right now due to #508. We may be able to adapt the video derivative action to pull directly from fedora instead of via flysystem, but that will need investigation.

**Comment by seth-shaw-asu** [comment]
Either completed or rolled into other items.
