### ISSUE TITLE
Very problematic complex objects.

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#570]
These complex objects have more than one issue. They either can’t be played at all or have only 6 seconds of accessible video, and some won’t generate thumbnail images. Some of the ones in the first link are listed in other hep tickets because I didn’t realize how multi-faceted the issues were: https://keep.lib.asu.edu/items/126980/members  

These two are the same as above, but aren’t not listed anywhere else in this document: https://keep.lib.asu.edu/items/126974/members https://keep.lib.asu.edu/items/127029/members

**Comment by seth-shaw-asu** [comment]
This is an issue with the original files. I checked a few in our backup of the previous repository and they are also bad files. I've kicked this back to Timothy to see if they have a good copy of these videos somewhere.
