### ISSUE TITLE
Unicode character glitch in title truncation for card-deck

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#578]
In the recently added item section on the home page for the State and Local Government Documents collection in PRISM, there seems to be an issue with the coding for apostrophes and possibly other characters. 
![Issue](https://user-images.githubusercontent.com/111911922/188018946-3d2824b2-dbff-40c8-9c24-fd15c01234ee.PNG)

**Comment by seth-shaw-asu** [comment]
The [latest items block](https://github.com/asulibraries/islandora-repo/blob/develop/web/modules/custom/asu_collection_extras/src/Plugin/Block/LatestAdditionsToCollectionBlock.php) uses the [collection_browse_teaser](https://keep.lib.asu.edu/admin/structure/types/manage/asu_repository_item/display/collection_browse_teaser) which uses the [complex_title_formatter](https://github.com/asulibraries/islandora-repo/blob/4111ac731b2084606666599e228b2a113a96b6e8/web/modules/custom/asu_search/src/Plugin/Field/FieldFormatter/ComplexTitleFormatter.php) which is then [trimmed by the display mode's twig template](https://github.com/asulibraries/islandora-repo/blob/c99d0caa602e395ea4110c96c49d3d3d77bd80ab/web/themes/custom/asulib_barrio/templates/content/node--asu-repository-item--recent-item-teaser.html.twig#L100-L106).

I.e. apparently something in `{% set title = content.field_title[0]|render|trim|slice(0, 60) %}` isn't unicode safe.
