### ISSUE TITLE
Qualys - Risk sense service now ticket items

### ISSUE THREAD

**Issue by stgurura** [asulibraries/islandora-repo#584]
Seth spent looking into the risk sense flags for Repo apps. Meeting with Dierdre to understand the action items and handling process. May continue into next week

**Comment by stgurura** [comment]
Talked to Dierdre about how to solve it and attended ITC risk monthly meeting. Need to talk to Dierdre again.

**Comment by seth-shaw-asu** [comment]
Addressed a log4j non-issue by clearing the gradle cache.

**Comment by stgurura** [comment]
Seth and Deirdre working on two more items that needs to be resolved

**Comment by stgurura** [comment]
As per Seth work is complete on this task now and future tickets will get a new work item
