### ISSUE TITLE
Fall 2022 - Barretts staff form access 

### ISSUE THREAD

**Issue by stgurura** [asulibraries/islandora-repo#606]
Hello Sandhya,

Thank you for reaching out! Cynthia retired from ASU this summer but I remain a good contact. For now, the following individuals need access to the staff form https://keep.lib.asu.edu/barrett-staff-form: 

Miranda Schultz – mgrimaud 
Matthew O’Brien – mjobrie1
Brody Frieden – btfriede 
Nicole Lindell – nlindell 
Jodi Menees – jmenees 
Jonathan Davis – jjdavis1

**Comment by seth-shaw-asu** [comment]
I've updated their accounts with the honors staff role.
