### ISSUE TITLE
Fall 2022 - Barretts student access

### ISSUE THREAD

**Issue by stgurura** [asulibraries/islandora-repo#607]
Hello Sandhya,

All active Barrett students need access to https://keep.lib.asu.edu/barrett-submission. However, they should only be able to complete the form*once*. Active Barrett student group codes include SRAE, SRAF, SRFR, SRFP, SRFQ. 

Thank you,

Miranda Schultz, M.Ed.

**Comment by seth-shaw-asu** [comment]
I put out a question to the library tech Slack channel to see if anyone knows how to verify that libauth is checking those codes.

**Comment by seth-shaw-asu** [comment]
It appears that this student code list does change periodically, as the existing check has a slightly different list. This update happens in libauth, so Stephen is taking care of it.

**Comment by seth-shaw-asu** [comment]
Stephen indicates that the update appears to have worked.

**Comment by stgurura** [comment]
Stephen Tanner
  [3 hours ago](https://asulib.slack.com/archives/GFFRPK7N1/p1665769922862769?thread_ts=1665760945.245449&cid=GFFRPK7N1)
I had to go and double-check it (since it changed a little bit when the data warehouse source we use shifted from Oracle to Postgres). The query driving that flag looks for a row that is marked "Active" with a group code that matches the regex
^SRA[E|F|G|H|M|N]$|^SRF[L|O|P|Q]$
So SRAE, SRAF, SRAG, SRAH, SRAM, SRAN, SRFL, SRFO, SRFP, SRFQ.
As I recall it was somewhat inconsistent how long each row would stay marked active (per semester?) but that was the list of codes we were told.


Seth Shaw
  [3 hours ago](https://asulib.slack.com/archives/GFFRPK7N1/p1665770044543559?thread_ts=1665760945.245449&cid=GFFRPK7N1)
Could we update the REGEX to include SRFR?


Stephen Tanner
  [3 hours ago](https://asulib.slack.com/archives/GFFRPK7N1/p1665770084969179?thread_ts=1665760945.245449&cid=GFFRPK7N1)
Yes.
It should update with the 11:00 batch run, I'll watch it to make sure.
