### ISSUE TITLE
Search for part of a complex/multi-part object

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#61]
:D

When the search view mode is used, the display twig should display a link to the complex object parent object -- and it should display "Part of {complex object parent -- linked to that content}" - since there is not a wireframe for the search display of any complex object children objects, it is not entirely clear whether or not the "Part of" be displayed as a label or if it should be bolded at all.

In order to identify these complex object children objects for processing in the preprocess theme event, the code will need to:

1. check for view mode search result highlighting
2. check for member of is an asu repository item with model 'complex object' and then set a variable with either that whole node or the title
3. then in the template check that variable and if its populated add the part of x?

This seems mostly handled how we need in the regular search but the collections search messes things up. The collections/search view needs to be modified to somehow include complex object children to the search.

**Comment by elizoller** [comment]
Need to figure out how to search deepest level but display the search result for the compound/parent object (ie one level below collection) and persist highlighting on the page/lower level

**Comment by wgilling** [comment]
added a "ancestors" field to the solr index that is configured to carry the hierarchy of the object's "Primary Member of" in the Processor config (via the solr module).

Will this need to return all children that have matched the search, or return the unified parent object in cases like that?

Should a search result return the parent object or each child?  I would think that in the case of paged content, it would be best to return only the book even if 33 pages met the search filter.

**Comment by elizoller** [comment]
i agree that just the parent object would be better to be displayed in the results, but i'm not sure how one aggregates that into the parent. the only immediate way i could think of would be like how you can "group" results based on a field in a view but i have no idea how that would interplay with search results (it for sure would need to be fields not rendered entities)

**Comment by elizoller** [comment]
i suspect we'll need to take advantage of the concept of a reverse entity reference - like the way we can search the full text of a media from the node.
if the initial collections chosen for migration do not include complex objects, this could happen after launch.
in addition, since the design will allow for a user to visit a "part" node page  - as long as they can get back to the "whole"/parent node - it wouldn't be the worst experience if they ended up there

**Comment by elizoller** [comment]
closed with #176
