### ISSUE TITLE
Alleviate repeated cache table locks

### ISSUE THREAD

**Issue by seth-shaw-asu** [asulibraries/islandora-repo#614]
Linda has been experiencing significant slowing, and occasional outright WSODs. The WSODs are associated with errors such as
```
2022/10/20 20:45:20 [error] 1129#1129: *84738 FastCGI sent in stderr: "PHP message: Uncaught PHP Exception Drupal\Core\Database\DatabaseExceptionWrapper: "SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction: INSERT INTO "cache_data" ("cid", "expire", "created", "tags", "checksum", "data", "serialized") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6) ON DUPLICATE KEY UPDATE "cid" = VALUES("cid"), "expire" = VALUES("expire"), "created" = VALUES("created"), "tags" = VALUES("tags"), "checksum" = VALUES("checksum"), "data" = VALUES("data"), "serialized" = VALUES("serialized"); Array
(
    [:db_insert_placeholder_0] => route:[language]=en:/admin/reports/dblog:page=0&severity%5B0%5D=0&severity%5B1%5D=1&severity%5B2%5D=2&severity%5B3%5D=3
    [:db_insert_placeholder_1] => -1
    [:db_insert_placeholder_2] => 1666298669.412
    [:db_insert_placeholder_3] => route_match
    [:db_insert_placeholder_"
while reading response header from upstream, client: X.X.X.X, server: keep.lib.asu.edu, request: "GET /admin/reports/dblog?severity%5B0%5D=0&severity%5B1%5D=1&severity%5B2%5D=2&severity%5B3%5D=3&page=0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "prism.lib.asu.edu"
```
There are _a lot_ of these database locking errors on cache tables. Clearing the cache appears to alleviate these issues for a while, but then they reappear.

**Comment by seth-shaw-asu** [comment]
I propose we abandon database-based cache management for Redis/AWS Elastic Cache. Redis is a more performant cache in the first place, bit it would also free up the database to perform queries only it can do. This option needs to be explored and tested on dev before we can use it in production.

@nightowlaz and I are also considering other database-specific solutions as well. E.g. there is [a long-standing issue discussing these errors on Drupal](https://www.drupal.org/project/drupal/issues/1650930) that may provide some guidance.

**Comment by stgurura** [comment]
Source: Linda's conversation on slack started this initially as a glitch but needed a deeper fix later.

**Comment by seth-shaw-asu** [comment]
@nightowlaz and I implemented an AWS ElastiCache instance on the dev site late last week and saw no adverse effects over the weekend. We implemented it again on production yesterday and will monitor the new setup over the course of the week to keep an eye out for any problems or cost concerns.

That said, I performed some searches as an anonymous user and was seeing reasonable TTFB results from 3 to 5 seconds with other pages arriving in milliseconds. This may be a bigger improvement than I expected.

**Comment by seth-shaw-asu** [comment]
Redis took a huge load off of the databases, and we've heard that at least navigating the site is a bit quicker, so we will call this a success.

@nightowlaz and I are still talking about right-sizing the ElastiCache and RDS instances, but I think we can close this issue.
