### ISSUE TITLE
Connections/relationships between objects

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#66]

**Comment by elizoller** [comment]
Is the only thing left for this adding the primary and additional memberships on the items brief metadata section?

**Comment by elizoller** [comment]
i think the last thing for this is to change the labels @dflitner do you have that one going?

**Comment by dflitner** [comment]
Yes! I had it done and then I imported develop config again. It looks great, if I say so myself :D

**Comment by dflitner** [comment]
I forgot to tag this issue separately but some commits in #126 should cover this.

**Comment by elizoller** [comment]
closed with #170
