### ISSUE TITLE
Ability to restore a deleted object

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#75]
might be satisfied by content moderation "archived" state, would need to remove all users ability to truly delete except for SUPER admins. probably also need a redirect module to handle cases where duplicates have been removed

**Comment by wgilling** [comment]
The first thought that I have is to change the content type of Islandora Object (Repository Item) nodes to a "tombstoned" content type.  This change will need to alter more than just the node table, but also the node_revision and the various field_values tables that reference it (see module below).  The benefit of this approach would be that the core drupal functions to display and search for nodes would still be useful to hide or show these to given roles and on given interfaces.

See the "Convert Bundles" module https://www.drupal.org/project/convert_bundles which is in alpha release and in use by only 600+ sites... it could be capable, but I need to ensure that the issues / concerns around that module still being an alpha are not going to ever cause us problems.

**Comment by wgilling** [comment]
I am concerned that all areas of the code that query the repository will be doing with the content_type already as part of the filtering.

**Comment by elizoller** [comment]
Verified that OAI feed is a view with a filter set to Repository Item. Likewise, SOLR can be configured to only index content of certain bundles (so we could exclude the deleted repository item content type).

**Comment by wgilling** [comment]
From a fresh claw-playbook VM, I installed the Convert Bundles module 
cd /var/www/html/drupal/web/modules/contrib
git clone --branch 8.x-1.x https://git.drupalcode.org/project/convert_bundles.git
drush pm-install convert_bundles.

After that is installed, I created a new object that I would soon "delete" by changing its content type from "Repository Item" to "Deleted Repository Item".  I only added one field to the deleted content type "Body".

The object view now displays a "Convert Bundle" tab:
![image](https://user-images.githubusercontent.com/19391126/74287261-c0429700-4ce6-11ea-8358-f4c402c4f728.png)

Clicking on that brings up a select box to allow you to see which content types you want to convert this to  
![image](https://user-images.githubusercontent.com/19391126/74287441-3515d100-4ce7-11ea-8297-a58fd47b9e7a.png)

and once you select the "Deleted Repository Item" and click [Next] button, the fields mappings page is displayed.  I could only select the "Body" field and attempt to map the Description field from the "Repository Item" content type.
![image](https://user-images.githubusercontent.com/19391126/74287535-68f0f680-4ce7-11ea-8250-71d3c767ef4b.png)

Now the checkbox on this screen seems to imply that the field values needed in the new target content type could be created if they do no exist yet.
![image](https://user-images.githubusercontent.com/19391126/74287613-976ed180-4ce7-11ea-9738-091965060e96.png)

The object has been converted and should not be showing up on the site anymore -- except for in a special view for "Deleted Repository Items" content -- yet, the object page does not display any field values other than Title and Body - which are default node fields.  The page DOES display the Convert Bundle tab... so, this could be used to convert it back to a "Repository Item" again and thereby _undelete it that way_.
![image](https://user-images.githubusercontent.com/19391126/74287851-2f6cbb00-4ce8-11ea-858e-6ee18a0fd181.png)

In the first page of converting that object, the only field that is able to be mapped is the "Body" field... going to go through with this while crossing my fingers.
![image](https://user-images.githubusercontent.com/19391126/74287957-735fc000-4ce8-11ea-9c83-0accc0bf9a71.png)

My instincts told me to not check this checkbox when mapping back to the real Repository Item content type - 
![image](https://user-images.githubusercontent.com/19391126/74288037-a3a75e80-4ce8-11ea-8281-c987af3758b5.png)

The convert process took much longer in this direction, but after it was done ALL OF THE DATA was where we need it for that object to be truly undeleted.
![image](https://user-images.githubusercontent.com/19391126/74288160-ec5f1780-4ce8-11ea-9b87-97e76a3adbc1.png)


more testing is needed to see how the deleted and undeleted objects are rendered in views, etc.

**Comment by elizoller** [comment]
After further discussion, we're thinking we could approach this concept with the Workflow and Content Moderation models where we have a state called Soft Delete (similar to the default shipped "Archive" state) that is unpublished. Then we would need a way to hook into when a node gets unpublished to fire certain actions in the context. We propose adding a piece in the hook_entity_update in https://github.com/Islandora/islandora/blob/8.x-1.x/islandora.module#L84 that would say if the object is unpublished then fire the Unpublish reactions which would be an additional action provided by Islandora.

**Comment by elizoller** [comment]
It would be ideal if we could determine when an object goes from published -> unpublished and only fire actions then. Danny thinks this is possible (although I didn't not think it would be). Will need testing.

**Comment by elizoller** [comment]
This is possible: https://github.com/asulibraries/islandora/tree/pub_unpub_actions

**Comment by wgilling** [comment]
requires some configurations:
- install groups module to control permissions for objects in a collection that "belongs" to somebody (work with @elizoller on restoring the "group roles" and config)
- limit permissions for who can delete
- adjust config for workflow to add a state called "Soft Deleted" and have it as a transition from Draft or Published object

**Comment by elizoller** [comment]
tasks left for this
1. remove the ability to actually delete - even for collection admins
2. put into config the start of the workflow including a soft deleted state - relate to https://github.com/asulibraries/islandora-repo/issues/72

**Comment by elizoller** [comment]
We might need to index workflow state - which would likely require a custom plugin for creating a search api processor

**Comment by wgilling** [comment]
- workflow configuration will need a "Soft Delete" state
- add the ability to really delete for collections managers (related to group config stuff - and part of core drupal permissions)
- (could configure the unpublish action to remove the item from the triplestore)

How would a user perform the soft delete function on an object in a collection???  Especially related to the group roles permission to do so.  

Addressing how this "delete" option will be displayed seems like it will need custom code that will alter pages and potentially add a plugin processor to get a solr field value indexed in order to use that for the group and perms.

**Comment by elizoller** [comment]
is it worth investigating the work done at FSU in this module: https://github.com/fsulib/tombstones

**Comment by wgilling** [comment]
the current approach is to write a module asu_soft_delete that will allow for handling the delete node logic.

this module should allow for overriding multiple content types ("ASU Repository Item", Collection, etc) in this way. This code will need to change the handler for the [Delete] button that appears on that form... in this submit handler, the code will simply be setting the publication status of the node to "Archived".

A view of the deleted nodes should be made to accompany this module. There should be a permission for accessing this form.

**Comment by wgilling** [comment]
this module is currently deployed under web/modules/custom/soft_delete

The configuration screen still displays the content types above the workflow states for each in separate sections -- and it would be nice to merge these two options together in an alternating fashion "enable Soft Delete handling for {content_type}" (checkbox) followed by a select box to pick which moderation_state value to set from the set of workflow states available to this content type.

There should be a minimal README before this can be released to the community.

**Comment by wgilling** [comment]
ready for review
