### ISSUE TITLE
Establish a Theme

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#79]
Likely can keep working off the fork of Carapace here: https://github.com/asulibraries/carapace
Will need to change ansible deployment to pull this into web/themes/custom instead of web/themes/contrib
Should probably work off a different branch than what is used for Islandora merges so we don't clutter than if we're going to contribute to it

**Comment by dflitner** [comment]
Just a side note, Carapace is a sub-theme of Adaptive Theme. ASU Marketing Hub/UTO is talking about a Drupal 8/9 theme for Webspark/Web Standards 2 based off of Bootstrap 4.

So we can go either way but either way we can match theme elements for our library Drupal site and our Islandora install that match ASU Web Standards.

**Comment by elizoller** [comment]
what are you thinking for the library Drupal site? the Bootstrap 4 approach?

**Comment by dflitner** [comment]
At the moment, I have Adaptive Theme installed. I'm used to how it works and I figured it'd be easier to match Islandora. I have no Bootstrap experience so I'm a little nervous about messing with that.

**Comment by elizoller** [comment]
A very beginning of theme has been established as a submodule to this repo and is located here: https://github.com/asulibraries/asulib-adaptive-subtheme

**Comment by elizoller** [comment]
Merged in new barrio bootstrap theme with https://github.com/asulibraries/islandora-repo/commit/02cce7c45ab482f80399c218a45d1851a1986b96
