### ISSUE TITLE
Handling Legacy Identifiers

### ISSUE THREAD

**Issue by elizoller** [asulibraries/islandora-repo#92]
How will we handle legacy identifiers and related routes like https://repository.asu.edu/items/53403.mods.xml ?

for early test migrations, i've stored the old system identifier in a specific field Legacy Identifier (machine name field_pid) 

should we consider enforcing those as nids? https://www.drupal.org/project/custom_nid

**Comment by elizoller** [comment]
Applying a custom bid sounds good but I’m wondering if there are conflicts between ids of different types coming from Django. Like their might be a collection with Id 1 and an item with id 1 but in drupal I think that isn’t possible since they are both nodes. 

Perhaps though we can create an alias based on the pid field?

**Comment by elizoller** [comment]
so i installed pathauto and configured url patterns like '/items/nid' and '/collections/nid' and it doesn't appear to break anything. however i chose nid instead of pid - if we do pid, we'd have to keep generating pids so i wasn't sure if we wanted to be in the business of doing that. should i bring to dev group?

**Comment by elizoller** [comment]
note that the alias doesn't get stored in the schema:sameAs in fedora - the default drupal /node/x format does - which is only mildly disappointing. i wonder if we could edit that - you know what would be better for that - the handle because that's a real, persistent URI

**Comment by elizoller** [comment]
@staceyerdman do you have thoughts

**Comment by staceyerdman** [comment]
Hmm, this is interesting. We definitely need some sort of permanent identifier for every item and collection, as that is key for preservation. I think using the handles would be the way to go here, although we could also store those legacy pids. The main thing is that we have institutional commitment to continue paying for the Handle service - which I think we do. We definitely can make the case that this is an important piece of our preservation strategy going forward. And if for some reason handle went away, we should be able to migrate to another solution pretty easily.

**Comment by elizoller** [comment]
Repo dev decided to stick with `/items/nid` and `/collections/nid` for now, but will hope to use something more descriptive in the future for exhibit like objects. This has been achieved with path auto configuration. Migrating the legacy identifiers to the PID field is also done already.
